### PR TITLE
[Publish_GitHub_Wiki_Content] Write-Build if $GitHubToken absent. Fixes Issue 75

### LINKED ISSUE #75: [Publish_GitHub_Wiki_Content] Write-Build if $GitHubToken not specified
When working with this module locally, significant time was spent to figure out why this task kept being skipped. The documentation for this task clearly states:

> The task will only run if the variable $GitHubToken is set either in parent scope, as an environment variable, or if passed to the build task.
> [Source](https://github.com/dsccommunity/DscResource.DocGenerator#publish_github_wiki_content)

However wouldn't it be more useful to output that status?

The current `Publish_GitHub_Wiki_Content.build.ps1` is as follows:

```powershell
task Publish_GitHub_Wiki_Content -if ($GitHubToken) {
...
}
```

What I'm proposing is something along the lines of:

```powershell
task Publish_GitHub_Wiki_Content {

    if ($GitHubToken)
    {
        # do same stuff

    } else {

        Write-Build SomeColor '$GitHubToken not set via parent scope, as an environment variable, or passed to the build task.'
        Write-Build SomeColor 'Skipping task: Publish_GitHub_Wiki_Content'
}
```

### PR DESCRIPTION
**Pull request by phbits**
### Pull Request (PR) description
Updated Task and Unit tests.

#### This Pull Request (PR) fixes the following issues

- Fixes #75 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated.
- [ ] Integration tests added/updated (where possible).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/77)

### CODE REVIEW

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/77)* status: all files reviewed, 10 unresolved discussions (waiting on @phbits)

___
*[source/tasks/Publish_GitHub_Wiki_Content.build.ps1, line 107 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/77#-MahQQJn1_SN5fVMjRCa:-MahQQJn1_SN5fVMjRCb:b-ejk42s) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/7e08ecf1a27a92eb1717ee2ce66c677a3c0518de/source/tasks/Publish_GitHub_Wiki_Content.build.ps1#L107)):*
> ```
>         Write-Build Yellow '$GitHubToken not set via parent scope, as an environment variable, or passed to the build task.'
>         Write-Build Yellow 'Skipping task: Publish_GitHub_Wiki_Content'
> ```

Suggest changing this to:

```
Write-Build Yellow 'Skipping task. Variable $GitHubToken not set via parent scope, as an environment variable, or passed to the build task.'`
```

It is gonna be obvious what task is skipped, so we won't need to output that. 
___
*[source/tasks/Publish_GitHub_Wiki_Content.build.ps1, line 110 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/77#-MahQsvGDt6CBSr_hHwl:-MahQsvGDt6CBSr_hHwm:b-vonnd8) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/7e08ecf1a27a92eb1717ee2ce66c677a3c0518de/source/tasks/Publish_GitHub_Wiki_Content.build.ps1#L110)):*
> ```
> } else {
> ```

Instead of using `else` can we just use `return` in the `if`-block above? If we gonna keep `else` then change the braces to
```
    }
    else
    {
``` 
___
*[tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1, line 44 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/77#-MahRMf1AWJt-nYkLXKw:-MahRMf1AWJt-nYkLXKx:b-bib3m2) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/7e08ecf1a27a92eb1717ee2ce66c677a3c0518de/tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1#L44)):*
> ```
> Context 'When $GitHubToken is specified.' {
> ```

We can remove the `.` in the Context-description.
___
*[tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1, line 44 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/77#-MahRWq6Dgt3IDl3FOOA:-MahRWq6Dgt3IDl3FOOB:bdus4i6) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/7e08ecf1a27a92eb1717ee2ce66c677a3c0518de/tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1#L44)):*
> ```
> Context 'When $GitHubToken is specified.' {
> ```

Please add a blank row before this row.
___
*[tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1, line 85 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/77#-MahRUj_0PPg6BEfd4Au:-MahRUja4jGUdO9Wy91T:bfig8yr) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/7e08ecf1a27a92eb1717ee2ce66c677a3c0518de/tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1#L85)):*
> ```
> Context 'When $GitHubToken is not specified.' {
> ```

We can remove the `.` in the Context-description.
___
*[tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1, line 85 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/77#-MahRb979UkY09kys0xL:-MahRb979UkY09kys0xM:bvga7i3) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/7e08ecf1a27a92eb1717ee2ce66c677a3c0518de/tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1#L85)):*
> ```
> Context 'When $GitHubToken is not specified.' {
> ```

Please add a blank row before this row.
___
*[tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1, line 89 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/77#-MahRdEW5Uvdq-bqq8gA:-MahRdEW5Uvdq-bqq8gB:bqwh2x1) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/7e08ecf1a27a92eb1717ee2ce66c677a3c0518de/tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1#L89)):*
> ```
> It 'Should Write-Build missing $GitHubToken & skipping task.' {
> ```

Please add a blank row before this row.
___
*[tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1, line 89 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/77#-MahS-A387YEujkKwdAX:-MahS-A387YEujkKwdAY:b-vul0tl) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/7e08ecf1a27a92eb1717ee2ce66c677a3c0518de/tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1#L89)):*
> ```
> It 'Should Write-Build missing $GitHubToken & skipping task.' {
> ```

We can remove the `.` in the It-description.
___
*[tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1, line 91 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/77#-MahRmKt1_fZVJA1IP1T:-MahRmKt1_fZVJA1IP1U:bv0aaek) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/7e08ecf1a27a92eb1717ee2ce66c677a3c0518de/tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1#L91)):*
> ```
> { Invoke-Build -Task $buildTaskName -File $script:buildScript.Definition @taskParameters
> ```

We should have the open brace on a separate row.

```
            {
                Invoke-Build -Task $buildTaskName -File $script:buildScript.Definition @taskParameters
            } | Should -Not -Throw
```
___
*[tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1, line 98 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/77#-MahRk0hCqviGUDxe15L:-MahRk0hCqviGUDxe15M:bxka06) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/7e08ecf1a27a92eb1717ee2ce66c677a3c0518de/tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1#L98)):*
> ```
> Assert-MockCalled -CommandName Write-Build -ParameterFilter {
> ```

Please add a blank row before this row.

**Review by phbits — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/77)* status: 1 of 3 files reviewed, 10 unresolved discussions (waiting on @johlju)

___
*[source/tasks/Publish_GitHub_Wiki_Content.build.ps1, line 107 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/77#-MahQQJn1_SN5fVMjRCa:-MaiMiY68k4K1H5fW2ky:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/7e08ecf1a27a92eb1717ee2ce66c677a3c0518de/source/tasks/Publish_GitHub_Wiki_Content.build.ps1#L107)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>         Write-Build Yellow '$GitHubToken not set via parent scope, as an environment variable, or passed to the build task.'
>         Write-Build Yellow 'Skipping task: Publish_GitHub_Wiki_Content'
> ```

Suggest changing this to:

```
Write-Build Yellow 'Skipping task. Variable $GitHubToken not set via parent scope, as an environment variable, or passed to the build task.'`
```

It is gonna be obvious what task is skipped, so we won't need to output that. 
</blockquote></details>

Done.
___
*[source/tasks/Publish_GitHub_Wiki_Content.build.ps1, line 110 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/77#-MahQsvGDt6CBSr_hHwl:-MaiQ8md-aTj5qbKS95f:bppjchp) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/7e08ecf1a27a92eb1717ee2ce66c677a3c0518de/source/tasks/Publish_GitHub_Wiki_Content.build.ps1#L110)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> } else {
> ```

Instead of using `else` can we just use `return` in the `if`-block above? If we gonna keep `else` then change the braces to
```
    }
    else
    {
``` 
</blockquote></details>

Suppose `return` may work though `if/else` is more readable. 
___
*[tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1, line 44 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/77#-MahRMf1AWJt-nYkLXKw:-MaiToWh9r4q83F0QM3i:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/7e08ecf1a27a92eb1717ee2ce66c677a3c0518de/tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1#L44)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Context 'When $GitHubToken is specified.' {
> ```

We can remove the `.` in the Context-description.
</blockquote></details>

Done.
___
*[tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1, line 44 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/77#-MahRWq6Dgt3IDl3FOOA:-MaiTq3b83tlo2RKMP8y:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/7e08ecf1a27a92eb1717ee2ce66c677a3c0518de/tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1#L44)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Context 'When $GitHubToken is specified.' {
> ```

Please add a blank row before this row.
</blockquote></details>

Done.
___
*[tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1, line 85 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/77#-MahRUj_0PPg6BEfd4Au:-MaiTsEL8L02djnNe3oa:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/7e08ecf1a27a92eb1717ee2ce66c677a3c0518de/tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1#L85)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Context 'When $GitHubToken is not specified.' {
> ```

We can remove the `.` in the Context-description.
</blockquote></details>

Done.
___
*[tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1, line 85 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/77#-MahRb979UkY09kys0xL:-MaiTv2M1biRGZkd-_Ri:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/7e08ecf1a27a92eb1717ee2ce66c677a3c0518de/tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1#L85)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Context 'When $GitHubToken is not specified.' {
> ```

Please add a blank row before this row.
</blockquote></details>

Done.
___
*[tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1, line 89 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/77#-MahRdEW5Uvdq-bqq8gA:-MaiU-OeCl_BKP61ZDlA:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/7e08ecf1a27a92eb1717ee2ce66c677a3c0518de/tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1#L89)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> It 'Should Write-Build missing $GitHubToken & skipping task.' {
> ```

Please add a blank row before this row.
</blockquote></details>

Done.
___
*[tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1, line 89 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/77#-MahS-A387YEujkKwdAX:-MaiU-zC-epZaoVkYwnF:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/7e08ecf1a27a92eb1717ee2ce66c677a3c0518de/tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1#L89)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> It 'Should Write-Build missing $GitHubToken & skipping task.' {
> ```

We can remove the `.` in the It-description.
</blockquote></details>

Done.
___
*[tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1, line 91 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/77#-MahRmKt1_fZVJA1IP1T:-MaiU1xZ8tiKnjz_N6L9:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/7e08ecf1a27a92eb1717ee2ce66c677a3c0518de/tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1#L91)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> { Invoke-Build -Task $buildTaskName -File $script:buildScript.Definition @taskParameters
> ```

We should have the open brace on a separate row.

```
            {
                Invoke-Build -Task $buildTaskName -File $script:buildScript.Definition @taskParameters
            } | Should -Not -Throw
```
</blockquote></details>

Done.
___
*[tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1, line 98 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/77#-MahRk0hCqviGUDxe15L:-MaiU32uB2fdqy-pLaPl:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/7e08ecf1a27a92eb1717ee2ce66c677a3c0518de/tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1#L98)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Assert-MockCalled -CommandName Write-Build -ParameterFilter {
> ```

Please add a blank row before this row.
</blockquote></details>

Done.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/77#-:-Mb6davj7DySFHU8ckCU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @phbits)

**Review by johlju — CHANGES_REQUESTED** [review]
The tests were failing, I missed that. Can you update the tests?

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/77#-:-Mb6eA4rE-ySr-DK_GPE:b-tyixhk)* status: all files reviewed, 2 unresolved discussions (waiting on @phbits)

___
*[tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1, line 100 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/77#-Mb6e5fpAIkRlbF0S-qC:-Mb6e5fpAIkRlbF0S-qD:bdq4uwv) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/3fa861132521e529ebe8bf13fa4ac80357c9d4b1/tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1#L100)):*
> ```
> $Text -eq '$GitHubToken not set via parent scope, as an environment variable, or passed to the build task.'
> ```

This assert need to be modified to code change.
___
*[tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1, line 103 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/77#-Mb6e0YWAdS_QyH37LAd:-Mb6e0YWAdS_QyH37LAe:b-s3adn2) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/3fa861132521e529ebe8bf13fa4ac80357c9d4b1/tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1#L103)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>             Assert-MockCalled -CommandName Write-Build -ParameterFilter {
>                 $Color -eq 'Yellow' -and
>                 $Text -eq 'Skipping task: Publish_GitHub_Wiki_Content'
>             } -Exactly -Times 1 -Scope It
> ```
</details>


This should removed.

**Review by phbits — COMMENTED** [review]
Doh! I missed that. :man_facepalming: Looks like everything is good to go now.

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/77#-:-Mb7nfCg1RvtdH_3mEuo:bgisble)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @johlju)

___
*[tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1, line 100 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/77#-Mb6e5fpAIkRlbF0S-qC:-Mb7ITU12yqAI0G8cFxT:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/3fa861132521e529ebe8bf13fa4ac80357c9d4b1/tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1#L100)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $Text -eq '$GitHubToken not set via parent scope, as an environment variable, or passed to the build task.'
> ```

This assert need to be modified to code change.
</blockquote></details>

Done.
___
*[tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1, line 103 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/77#-Mb6e0YWAdS_QyH37LAd:-Mb7IUhw2FVyIZvVbLgZ:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/3fa861132521e529ebe8bf13fa4ac80357c9d4b1/tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1#L103)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>             Assert-MockCalled -CommandName Write-Build -ParameterFilter {
>                 $Color -eq 'Yellow' -and
>                 $Text -eq 'Skipping task: Publish_GitHub_Wiki_Content'
>             } -Exactly -Times 1 -Scope It
> ```

This should removed.
</blockquote></details>

Done.

**Review by johlju — APPROVED** [review]
:lgtm:

No worries! :smiley: Looks good now.

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/77#-:-MbGAf5RBKITxXDUec4h:boigklq)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @johlju)

**Review by johlju — APPROVED** [review]

**Pull request merged**
