### PR TITLE
`New-DscResourceWikiPage`: Add support for inherited properties from base class

### LINKED ISSUE #62: New-DscResourceWikiPage: Should generate inherited properties from base class for class-based resources
Class-based resource can inherit DSC resource properties from it's base class. Those should also be generated documentation for. Base classes should be found recursively since a base class can in turn inherit.

### PR DESCRIPTION
**Pull request by johlju**
# Pull Request

### Pull Request (PR) description
- Added private functions:
  - `Get-ClassAst` - Returns the AST for a single or all classes.
  - `Get-ClassResourceAst` - Returns the AST for a single or all DSC class
    resources.
  - `Get-ClassResourceProperty` - Returns DSC class resource properties
    from the provided class or classes.
  - `Format-Text` - Format a string according to predefined options.
- `New-DscResourceWikiPage`
  - If a class-based resource have a parent class that contains DSC resource
    properties they will now also be returned as part of the DSC resource
    parameters ([issue #62](https://github.com/dsccommunity/DscResource.DocGenerator/issues/62)).

#### This Pull Request (PR) fixes the following issues

- Fixes #62

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Documentation added/updated in README.md.
- [x] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated.
- [ ] Integration tests added/updated (where possible).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/78)

### CODE REVIEW

**Comment by johlju** [comment]
Need to add unit tests for the new private functions and the new functionality for parent classes.

**Comment by johlju** [comment]
@PlagueHO do you have time to review this? 🙂

**Comment by johlju** [comment]
Prior to this change properties from parent classes was not generated to the Wiki pages. See example prior to this change here:
https://github.com/dsccommunity/DnsServerDsc/wiki/DnsRecordA

Running the build task using the changes in this PR added the properties from the base class:
image
image

**Comment by PlagueHO** [comment]
Yep! Will have time tonight after work

**Review by PlagueHO — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/78)* status: all files reviewed, 9 unresolved discussions (waiting on @johlju)

___
*[CHANGELOG.md, line 20 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/78#-MbAGEGs5ZRcE_EYeUF0:-MbAGEGs5ZRcE_EYeUF1:b-8aum1j) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/6f883406cea24410d51c701b5875d86487e7cc9d/CHANGELOG.md#L20)):*
> ```
>  - If a class-based resource has a parent class that contains DSC resource
> ```
___
*[source/Private/Get-ClassAst.ps1, line 49 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/78#-MbAGVTmBLkX8PuHCWd4:-MbAGVTmBLkX8PuHCWd5:boq0ocs) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/6f883406cea24410d51c701b5875d86487e7cc9d/source/Private/Get-ClassAst.ps1#L49)):*
Nitpick:
> ```
> -and $args[0].IsClass `
> ```
___
*[source/Private/Get-ClassAst.ps1, line 58 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/78#-MbAGZNY0Z-U276Nuqsx:-MbAGZNY0Z-U276Nuqsy:bowhly) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/6f883406cea24410d51c701b5875d86487e7cc9d/source/Private/Get-ClassAst.ps1#L58)):*
Nitpick:
> ```
>  -and $args[0].IsClass
> ```
___
*[source/Private/Get-ClassResourceAst.ps1, line 54 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/78#-MbAGiCHEpZe5-1PY0DJ:-MbAGiCHEpZe5-1PY0DK:boq0ocs) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/6f883406cea24410d51c701b5875d86487e7cc9d/source/Private/Get-ClassResourceAst.ps1#L54)):*
Nitpick:
> ```
> -and $args[0].IsClass `
> ```
___
*[source/Private/Get-ClassResourceProperty.ps1, line 9 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/78#-MbAH-CtADzEzvEUQK91:-MbAH-CtADzEzvEUQK92:b-2g6o1p) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/6f883406cea24410d51c701b5875d86487e7cc9d/source/Private/Get-ClassResourceProperty.ps1#L9)):*
> ```
> The path to the built module script file that contains the class.
> ```
___
*[source/Private/Get-ClassResourceProperty.ps1, line 21 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/78#-MbAJB0jBn_sYLyItSdC:-MbAJB0jBn_sYLyItSdD:bmpu4pu) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/6f883406cea24410d51c701b5875d86487e7cc9d/source/Private/Get-ClassResourceProperty.ps1#L21)):*
> ```PowerShell
> function Get-ClassResourceProperty
> {
>     [CmdletBinding()]
> ```

Can we specify an output type for this function? Looks like an array?
___
*[source/Private/Get-ClassResourceProperty.ps1, line 103 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/78#-MbAIYotBKn0I-Qiex7N:-MbAIYotBKn0I-Qiex7O:b-1gc7ug) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/6f883406cea24410d51c701b5875d86487e7cc9d/source/Private/Get-ClassResourceProperty.ps1#L103)):*
> ```PowerShell
>                 $propertyDescription = ($dscResourceCommentBasedHelp.Parameters[$propertyMemberAst.Name.ToUpper()] -replace '[\r|\n]+$')
> 
>                 $propertyDescription = $propertyDescription -replace '[\r|\n]+$' # Removes all blank rows at the end
> ```

It seems like this whole block is a generic "table cleanup". I wonder if this block should be extracted into some sort of clean up function that can be more easily tested.
___
*[tests/unit/public/New-DscResourceWikiPage.Tests.ps1, line 1444 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/78#-MbAKaCdDle0VpMHrORh:-MbAKaCeDvAp00qB9tCB:bkjqmab) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/6f883406cea24410d51c701b5875d86487e7cc9d/tests/unit/public/New-DscResourceWikiPage.Tests.ps1#L1444)):*
> ```
> Context 'When the resource has a parent class that also has a DSC property' {
> ```
___
*[tests/unit/public/New-DscResourceWikiPage.Tests.ps1, line 1625 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/78#-MbALpsj6jlJV70Jh0IC:-MbALpsj6jlJV70Jh0ID:b-ogmyok) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/6f883406cea24410d51c701b5875d86487e7cc9d/tests/unit/public/New-DscResourceWikiPage.Tests.ps1#L1625)):*
> ```
> Context 'When the resource has a parent class that also have a DSC property, but the property does not have a parameter description' {
> ```

**Review by johlju — COMMENTED** [review]
> Reviewed 3 of 6 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/78)* status: all files reviewed, 9 unresolved discussions (waiting on @johlju and @PlagueHO)

___
*[CHANGELOG.md, line 20 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/78#-MbAGEGs5ZRcE_EYeUF0:-MbG9nEAEXdbxwyAGmzA:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/6f883406cea24410d51c701b5875d86487e7cc9d/CHANGELOG.md#L20)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

> ```
>  - If a class-based resource has a parent class that contains DSC resource
> ```

</blockquote></details>

Done.
___
*[source/Private/Get-ClassAst.ps1, line 49 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/78#-MbAGVTmBLkX8PuHCWd4:-MbG9nyEEu-n4yOUllKN:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/6f883406cea24410d51c701b5875d86487e7cc9d/source/Private/Get-ClassAst.ps1#L49)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick:
> ```
> -and $args[0].IsClass `
> ```

</blockquote></details>

Done.
___
*[source/Private/Get-ClassAst.ps1, line 58 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/78#-MbAGZNY0Z-U276Nuqsx:-MbG9oMxDOxL_UMDJfod:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/6f883406cea24410d51c701b5875d86487e7cc9d/source/Private/Get-ClassAst.ps1#L58)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick:
> ```
>  -and $args[0].IsClass
> ```

</blockquote></details>

Done.
___
*[source/Private/Get-ClassResourceAst.ps1, line 54 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/78#-MbAGiCHEpZe5-1PY0DJ:-MbG9ox68NW8rx4hBP_F:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/6f883406cea24410d51c701b5875d86487e7cc9d/source/Private/Get-ClassResourceAst.ps1#L54)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick:
> ```
> -and $args[0].IsClass `
> ```

</blockquote></details>

Done.
___
*[source/Private/Get-ClassResourceProperty.ps1, line 9 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/78#-MbAH-CtADzEzvEUQK91:-MbG9qJe77a3BMX9TpOV:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/6f883406cea24410d51c701b5875d86487e7cc9d/source/Private/Get-ClassResourceProperty.ps1#L9)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

> ```
> The path to the built module script file that contains the class.
> ```

</blockquote></details>

Done.
___
*[source/Private/Get-ClassResourceProperty.ps1, line 21 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/78#-MbAJB0jBn_sYLyItSdC:-MbG9r7P7n2DGFdxtU8n:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/6f883406cea24410d51c701b5875d86487e7cc9d/source/Private/Get-ClassResourceProperty.ps1#L21)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can we specify an output type for this function? Looks like an array?
</blockquote></details>

Done.
___
*[tests/unit/public/New-DscResourceWikiPage.Tests.ps1, line 1444 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/78#-MbAKaCdDle0VpMHrORh:-MbGAL8E66eJll5JWwo5:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/6f883406cea24410d51c701b5875d86487e7cc9d/tests/unit/public/New-DscResourceWikiPage.Tests.ps1#L1444)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

> ```
> Context 'When the resource has a parent class that also has a DSC property' {
> ```

</blockquote></details>

Done.
___
*[tests/unit/public/New-DscResourceWikiPage.Tests.ps1, line 1625 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/78#-MbALpsj6jlJV70Jh0IC:-MbGAJO26qj5WQFeexNk:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/6f883406cea24410d51c701b5875d86487e7cc9d/tests/unit/public/New-DscResourceWikiPage.Tests.ps1#L1625)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

> ```
> Context 'When the resource has a parent class that also have a DSC property, but the property does not have a parameter description' {
> ```

</blockquote></details>

Done.

**Review by johlju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/78)* status: all files reviewed, 9 unresolved discussions (waiting on @PlagueHO)

___
*[source/Private/Get-ClassResourceProperty.ps1, line 103 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/78#-MbAIYotBKn0I-Qiex7N:-MbGAR7UAquaR5CZRiQH:b7haqec) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/6f883406cea24410d51c701b5875d86487e7cc9d/source/Private/Get-ClassResourceProperty.ps1#L103)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

It seems like this whole block is a generic "table cleanup". I wonder if this block should be extracted into some sort of clean up function that can be more easily tested.
</blockquote></details>

I can fix that, also realized I missed making an entire unit test for this function. Will break out this, it will close issue https://github.com/dsccommunity/DscResource.DocGenerator/issues/58 too. Will work on that this weekend.

**Review by johlju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/78)* status: 6 of 11 files reviewed, 9 unresolved discussions (waiting on @johlju and @PlagueHO)

___
*[source/Private/Get-ClassResourceProperty.ps1, line 103 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/78#-MbAIYotBKn0I-Qiex7N:-MbR9yPd2B66Oc6T4Zsn:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/6f883406cea24410d51c701b5875d86487e7cc9d/source/Private/Get-ClassResourceProperty.ps1#L103)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

I can fix that, also realized I missed making an entire unit test for this function. Will break out this, it will close issue https://github.com/dsccommunity/DscResource.DocGenerator/issues/58 too. Will work on that this weekend.
</blockquote></details>

Done.

**Comment by johlju** [comment]
@PlagueHO this is ready for review again. I couldn't close the issue I mentioned in this PR because it was part of another part of the module that also need to be updated similar to this, so I will leave it for another PR (it is tracked in yet another issue).

**Review by PlagueHO — CHANGES_REQUESTED** [review]
Just one minor tweak :grin:

> Reviewed 2 of 5 files at r3, 4 of 5 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/78#-:-Mb_NQQ38red1HOTewXJ:b-dj7kwe)* status: all files reviewed, 1 unresolved discussion (waiting on @johlju)

___
*[source/Private/Format-Text.ps1, line 42 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/78#-Mb_MbT42o2QkaEp71dc:-Mb_MbT42o2QkaEp71dd:bcw7pnh) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/edd5c356d2d48ca418898aae065037f19c97e8ae/source/Private/Format-Text.ps1#L42)):*
> ```PowerShell
>     $returnString = $Text
> 
>     # This will loop through each format.
> ```

The comment doesn't align to the actual code (e.g. not a loop). I don't think it is needed anyway - pretty clear the intent.

**Review by johlju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/78)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @PlagueHO)

___
*[source/Private/Format-Text.ps1, line 42 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/78#-Mb_MbT42o2QkaEp71dc:-Mb_Q2Rz4wOJAMq8LKCP:b-3eq4nq) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/edd5c356d2d48ca418898aae065037f19c97e8ae/source/Private/Format-Text.ps1#L42)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

The comment doesn't align to the actual code (e.g. not a loop). I don't think it is needed anyway - pretty clear the intent.
</blockquote></details>

Done. I didn't know switch would actually iterate through the array automatically, so I added a comment for others, but agree it is not necessary. ;)

**Pull request merged**
