### PR TITLE
Added Additional Functions to prepare Composite Resource support

### PR DESCRIPTION
**Pull request by PlagueHO**
# Pull Request

### Pull Request (PR) description

This PR adds the requisite support functions to enable Composite resource support. The actual support is not yet included as I wanted to limit the amount of change (still too much change for one PR really). Relates to #79 

#### This Pull Request (PR) fixes the following issues

- None.

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Documentation added/updated in README.md.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated.
- [ ] Integration tests added/updated (where possible).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

@johlju - would you mind reviewing this when you have time? Once this one is through it should be a reasonably straight shot to enable composite support.

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/83)

### CODE REVIEW

**Review by johlju — APPROVED** [review]
:lgtm:

This looks good to me when the tests passes. 

> Reviewed 17 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/83#-:-McZiUjB2FbeirsOlM5i:bllkwjg)* status: all files reviewed, 3 unresolved discussions (waiting on @PlagueHO)

___
*[source/Private/Get-ConfigurationAst.ps1, line 55 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/83#-McZeTWvBQGjmCgA9PUJ:-McZeTWvBQGjmCgA9PUK:b1bg4cm) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/26b6bf5bec9f65d1625d026686bfa311be9f60d0/source/Private/Get-ConfigurationAst.ps1#L55)):*
> ```
> Get only the specific class resource.
> ```

Should this say '...specific composite resource...'?
___
*[source/Private/Get-ConfigurationAst.ps1, line 64 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/83#-McZeeryAudhHMaJefU9:-McZeeryAudhHMaJefUA:ba1mec0) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/26b6bf5bec9f65d1625d026686bfa311be9f60d0/source/Private/Get-ConfigurationAst.ps1#L64)):*
> ```
> # Get all class resources.
> ```

Should this say '...composite resource...'?
___
*[tests/unit/private/Get-CompositeResourceParameterState.Tests.ps1, line 62 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/83#-McZfj8y0P2REmU8x4-H:-McZfj8y0P2REmU8x4-I:bympadd) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/26b6bf5bec9f65d1625d026686bfa311be9f60d0/tests/unit/private/Get-CompositeResourceParameterState.Tests.ps1#L62)):*
> ```
> [ValidateNotNullOrEmpty()]
> ```

Not needed for a `Mandatory` parameter. :thinking:  But maybe we are testing parsing of this?

**Comment by johlju** [comment]
@PlagueHO conflicting files that also needs to resolved since I merged a PR.

**Review by PlagueHO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/83)* status: 15 of 17 files reviewed, 3 unresolved discussions (waiting on @johlju)

___
*[source/Private/Get-ConfigurationAst.ps1, line 55 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/83#-McZeTWvBQGjmCgA9PUJ:-Mca-nFN500tHNIbqV3X:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/26b6bf5bec9f65d1625d026686bfa311be9f60d0/source/Private/Get-ConfigurationAst.ps1#L55)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Get only the specific class resource.
> ```

Should this say '...specific composite resource...'?
</blockquote></details>

Done.
___
*[source/Private/Get-ConfigurationAst.ps1, line 64 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/83#-McZeeryAudhHMaJefU9:-Mca-oeK9OEcVX40r3kR:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/26b6bf5bec9f65d1625d026686bfa311be9f60d0/source/Private/Get-ConfigurationAst.ps1#L64)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> # Get all class resources.
> ```

Should this say '...composite resource...'?
</blockquote></details>

Done.
___
*[tests/unit/private/Get-CompositeResourceParameterState.Tests.ps1, line 62 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/83#-McZfj8y0P2REmU8x4-H:-Mca-pS-D42pokaPFuzd:b-2aqa6c) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/26b6bf5bec9f65d1625d026686bfa311be9f60d0/tests/unit/private/Get-CompositeResourceParameterState.Tests.ps1#L62)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> [ValidateNotNullOrEmpty()]
> ```

Not needed for a `Mandatory` parameter. :thinking:  But maybe we are testing parsing of this? 
</blockquote></details>

Agreed. I was considering this as we can supply a lot more information for a composite resource than we can a MOF resource. I was also thinking about detecting default values - could technically do defaults in MOF/Class resources too if we wanted. I'll add this in once I get things working :/

**Review by PlagueHO — COMMENTED** [review]
Ok, should be good to go now @johlju - can you have a look at the changes?

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/83#-:-McbEO-225MmNLewJ8Nb:bd0l677)* status: 12 of 19 files reviewed, 3 unresolved discussions (waiting on @johlju)

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 6 of 7 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/83#-:-McdW0fZBqHTq6ACqlec:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PlagueHO)

**Comment by johlju** [comment]
This is merged now.

**Comment by johlju** [comment]
@PlagueHO awesome work on this! 😃

**Pull request merged**
