### PR TITLE
Get-CompositeSchemaObject now handles missing comment-based help (minor bump)

### PR DESCRIPTION
**Pull request by raandree**
# Pull Request

### Pull Request (PR) description
Common task variables have not been set, fixed that by calling `Set-SamplerTaskVariable`

#### This Pull Request (PR) fixes the following issues
Closes https://github.com/gaelcolas/Sampler/issues/361
Fixes https://github.com/dsccommunity/DscResource.DocGenerator/issues/82

#### Task list
- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated.
- [ ] Integration tests added/updated (where possible).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/117)

### CODE REVIEW

**Review by johlju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/117)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @johlju and @raandree)

___
*[source/tasks/Generate_Wiki_Content.build.ps1, line 71 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/117#-N0C73ra2VYAJ0heu7E7:-N0C73rbAFElHJjJq-Kk:bmmi1mw) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/88f9ac6e0cf1fa791c8f7f7970030847b87d0291/source/tasks/Generate_Wiki_Content.build.ps1#L71)):*
> ```PowerShell
>     [Parameter()]
>     [System.String]
>     $ProjectName = (property ProjectName $(Get-SamplerProjectName -BuildRoot $BuildRoot)),
> ```

I think we need to clean up the parameters too when we are moving to use `. Set-SamplerTaskVariable`

Looking at the parameters in Sampler build tasks this one should for example be:
```
$ProjectName = (property ProjectName ''),
```



_Code quote:_
```PowerShell
$ProjectName = (property ProjectName $(Get-SamplerProjectName -BuildRoot $BuildRoot)),
```

**Comment by raandree** [comment]
It's weird, the issue is in Set-SamplerTaskVariable.ps1::161

```powershell
$BuiltModuleManifest = Get-SamplerBuiltModuleManifest @GetBuiltModuleManifestParams #returns a string
if ($BuiltModuleManifest)
{
    $BuiltModuleManifest = (Get-Item -Path $BuiltModuleManifest -ErrorAction 'SilentlyContinue').FullName #returns an array
}
```

```
[DBG]: PS D:\> $BuiltModuleManifest

D:\DscResource.DocGenerator\output\MyModule\99.1.1\MyModule.psd1
[DBG]: PS D:\> $BuiltModuleManifest.Count

1
[DBG]: PS D:\> $BuiltModuleManifest.GetType()


IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     Object[]                                 System.Array
```

This is why the error `Cannot process argument transformation on parameter 'ModuleManifestPath'. Cannot convert value to type System.String` is thrown when calling `Get-SamplerModuleRootPath`.

**Comment by raandree** [comment]
@johlju, do you want parameter default value assignments to be replaced? Is the pattern to remove the `Get-Sampler*` function call and replace if with the usual property assignment?

**Comment by johlju** [comment]
> @johlju, do you want parameter default value assignments to be replaced? Is the pattern to remove the `Get-Sampler*` function call and replace if with the usual property assignment?

The default values was made after how Sampler's task was made before they were changed. The task in [Sampler.GitHubTasks](https://github.com/gaelcolas/Sampler.GitHubTasks/blob/main/.build/tasks/New-Release.GitHub.build.ps1) is the last one created and I think we should follow that pattern. I don't think it should break anything, but instead make it better. 🤔

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/117)* status: all files reviewed, 2 unresolved discussions (waiting on @raandree)

___
*[CHANGELOG.md, line 11 at r3](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/117#-N0H_rEb8t3oRQQho-uj:-N0H_rEb8t3oRQQho-uk:b-1vh8rl) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/e495f674ccc7d037fef6510aa4d107237886ff27/CHANGELOG.md#L11)):*
> ```Markdown
> 
> - Common task variables have not been set, fixed that.
> - `Get-CompositeSchemaObject` threw an error when a composite did not have comment based help, how returns `$null`.
> ```

Should be 'now returns'?



_Code quote:_
```Markdown
how returns
```

**Comment by johlju** [comment]
@raandree I changed how it handles missing comment-based help, hoping this will work. What do you think?

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 3 of 8 files at r4, 3 of 3 files at r5, 4 of 5 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/117#-:-N1dgKZh2Jp0Mwz3r3iZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @raandree)

**Pull request merged**
