### PR TITLE
Handle existing sidebar file during publish

### LINKED ISSUE #105: Add DoNotOverwriteSidebar option in the Publish_GitHub_Wiki_Content task
#### Details of the scenario you tried and the problem that is occurring

The current code of the Publish_GitHub_Wiki_Content task always generates a new Wiki sidebar markdown file: https://github.com/dsccommunity/DscResource.DocGenerator/blob/main/source/Private/New-WikiSidebar.ps1#L54-L61

For my repo I am using a custom side bar and don't want it to be overwritten. Please add a possibility to specify that you don't want the sidebar to be overwritten, so I can start using the task to automatically update the wiki content.

#### Steps to reproduce the problem

Publish a new version in a repo that uses this task, it will always overwrite the sidebar

#### Expected behavior

Specify a parameter to prevent the creation of a new sidebar.

#### Current behavior

Will always overwrite the sidebar

#### Suggested solution to the issue

Add a parameter somewhere to specify you don't want the sidebar to be generated.

#### The operating system the target node is running

N/A

#### Version and build of PowerShell the target node is running

N/A

#### Version of the module that was used

Most recent

### PR DESCRIPTION
**Pull request by johlju**
# Pull Request

### Pull Request (PR) description

- When there is an existing `_Sidebar.md` in the folder 'WikiSource' that is
  copied to the folder 'WikiContent', it will no longer be overwritten
  during publish (issue #105).

#### This Pull Request (PR) fixes the following issues
- Fixes #105

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated.
- [ ] Integration tests added/updated (where possible).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/106)

### CODE REVIEW

**Comment by ykuijs** [comment]
Don't think the new behavior of the function in this PR is the desired behavior:
What if you release a new version, which generates a sidebar. Then with the next release, you want the sidebar to be updated, for example because new resources has been added for which documentation has been generated that should be added to the sidebar as well. But since the WikiSource already contains the previously generated sidebar, with this change a new sidebar will never be updated after it was generated once.

I think the toggle I suggested in the issue would make more sense. Then the repo owner can specify if he wants the sidebar to be generated or not.

**Comment by johlju** [comment]
The comment @ykuijs made was a misunderstanding that was cleared out in the discussion in the issue #105.

**Review by PlagueHO — CHANGES_REQUESTED** [review]
Great job @johlju - just some minor wording tweaks.

> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/106#-:-Mu8hHVL5Qjrj-apEZ_0:bmr646a)* status: all files reviewed, 4 unresolved discussions (waiting on @johlju)

___
*[CHANGELOG.md, line 13 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/106#-Mu8gVYZ5G1c2YnAYZxd:-Mu8gVYZ5G1c2YnAYZxe:b-qm4afu) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/a1c564e9f7ab216318fdda42f91163f80e21c72b/CHANGELOG.md#L13)):*
> ```Markdown
>   copied to the folder 'WikiContent', it will no longer be overwritten
>   during publish ([issue #105](https://github.com/dsccommunity/DscResource.DocGenerator/issues/105)).
> - Fixed unit tests for the task `Publish_GitHub_Wiki_Content` due to failing
> ```

Perhaps:



_Suggestion:_
```Markdown
- Fixed failing unit tests for the task `Publish_GitHub_Wiki_Content`.
```
___
*[CHANGELOG.md, line 15 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/106#-Mu8fgp8D2LnSqT1GPX1:-Mu8fgp8D2LnSqT1GPX2:b-qm4afu) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/a1c564e9f7ab216318fdda42f91163f80e21c72b/CHANGELOG.md#L15)):*
> ```Markdown
> - Fixed unit tests for the task `Publish_GitHub_Wiki_Content` due to failing
>   tests.
> - Moved around and rephrased some texts in the README.md so it better match
> ```

Perhaps:



_Suggestion:_
```Markdown
- Rearranged and rephrased some text in the README.md to increase
  clarity. Previously some documentation that applied to a task, but
  should have applied to the command that the task that called it.
```
___
*[README.md, line 98 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/106#-Mu8ggj_15dcq6AXn_2P:-Mu8ggj_15dcq6AXn_2Q:b-qm4afu) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/a1c564e9f7ab216318fdda42f91163f80e21c72b/README.md#L98)):*
> ```Markdown
> It is possible to use markdown code in the schema MOF parameter descriptions.
> If markdown code is used and conceptual help is also to be generated, configure
> the task [`Generate_Conceptual_Help`](#generate_conceptual_help) to parse
> ```

Perhaps:



_Suggestion:_
```Markdown
the task [`Generate_Conceptual_Help`](#generate_conceptual_help) to parse the
```
___
*[README.md, line 339 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/106#-Mu8h2bZBNhj-rgPHTou:-Mu8h2bZBNhj-rgPHTov:bw4zrkn) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/a1c564e9f7ab216318fdda42f91163f80e21c72b/README.md#L339)):*
> ```Markdown
> (the parameter `WikiSourceFolderName` defaults to `WikiSource`). The wiki
> source folder should be located under the source folder, e.g. `source/WikiSource`.
> The wiki source folder it is meant to contain additional documentation that
> ```

Correction:



_Suggestion:_
```Markdown
The wiki source folder is meant to contain additional documentation that
```

**Review by johlju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/106)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @PlagueHO)

___
*[CHANGELOG.md, line 13 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/106#-Mu8gVYZ5G1c2YnAYZxd:-MuA9iQxD4ErBiVsInti:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/a1c564e9f7ab216318fdda42f91163f80e21c72b/CHANGELOG.md#L13)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Perhaps:
</blockquote></details>

Done.
___
*[CHANGELOG.md, line 15 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/106#-Mu8fgp8D2LnSqT1GPX1:-MuA9nfe1dRQ3O2cmp-i:bs7wumx) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/a1c564e9f7ab216318fdda42f91163f80e21c72b/CHANGELOG.md#L15)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Perhaps:
</blockquote></details>

Done. 
___
*[README.md, line 98 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/106#-Mu8ggj_15dcq6AXn_2P:-MuA9v7j3k5iwTqgllQE:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/a1c564e9f7ab216318fdda42f91163f80e21c72b/README.md#L98)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Perhaps:
</blockquote></details>

Done.
___
*[README.md, line 339 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/106#-Mu8h2bZBNhj-rgPHTou:-MuA9vpIEjBn2SNcop-A:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/a1c564e9f7ab216318fdda42f91163f80e21c72b/README.md#L339)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Correction:
</blockquote></details>

Done.

**Comment by johlju** [comment]
@PlagueHO ready for review again. 🙂

**Review by PlagueHO — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/106#-:-MuCT-7_CuHmVWA1i3MR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johlju)

**Pull request merged**
