### PR TITLE
Complete Support for Composite Resources in Wiki pages

### LINKED ISSUE #79: Add Support for Composite Resources
The xPSDesiredStateConfiguration module has several Composite resources. Auto-documentation generation does not currently work with these resources.

We should add support for these.

### PR DESCRIPTION
**Pull request by PlagueHO**
# Pull Request

### Pull Request (PR) description

This PR adds support for composite resources to `New-DscResourceWikiPage`.

#### This Pull Request (PR) fixes the following issues

- Fixes #79 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Documentation added/updated in README.md.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated.
- [x] Integration tests added/updated (where possible).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

@johlju - would you mind reviewing for me when you have time?

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/97)

### CODE REVIEW

**Review by johlju — COMMENTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/97)* status: all files reviewed, 1 unresolved discussion (waiting on @PlagueHO)

___
*[source/Private/New-DscCompositeResourceWikiPage.ps1, line 70 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/97#-MeKMfp63M2OvmmT23E9:-MeKMfp63M2OvmmT23EA:b-vzrty7) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/fdc2b99bc287752b2ba5be48b5b61bb7adbd05da/source/Private/New-DscCompositeResourceWikiPage.ps1#L70)):*
> ```
> $_.Name -like 'readme.md'
> ```

On Linux will this fail if the filename happens to be `ReadMe.md` or `README.md`? Maybe we should use regex instead? :thinking:

**Comment by johlju** [comment]
@PlagueHO awesome work! Just one comment, that I could see.

**Review by PlagueHO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/97)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PlagueHO)

___
*[source/Private/New-DscCompositeResourceWikiPage.ps1, line 70 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/97#-MeKMfp63M2OvmmT23E9:-MeO6WK_5eMuqUJsUSYz:b-p1lpab) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/fdc2b99bc287752b2ba5be48b5b61bb7adbd05da/source/Private/New-DscCompositeResourceWikiPage.ps1#L70)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $_.Name -like 'readme.md'
> ```

On Linux will this fail if the filename happens to be `ReadMe.md` or `README.md`? Maybe we should use regex instead? :thinking:  
</blockquote></details>

`-like` is case insensitive (`-clike` is case sensitive) - so this should work on Linux and Windows. Also, copied from `New-DscMofRewsourceWikiPage.ps1` :laughing:

**Review by johlju — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/97)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PlagueHO)

___
*[source/Private/New-DscCompositeResourceWikiPage.ps1, line 70 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/97#-MeKMfp63M2OvmmT23E9:-MeOLoyD9SR3mxOqME8P:bqw3rq) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/fdc2b99bc287752b2ba5be48b5b61bb7adbd05da/source/Private/New-DscCompositeResourceWikiPage.ps1#L70)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

`-like` is case insensitive (`-clike` is case sensitive) - so this should work on Linux and Windows. Also, copied from `New-DscMofRewsourceWikiPage.ps1` :laughing: 
</blockquote></details>

Yes, right. Didn’t think of that. Not sure what I thought 😆 All good then :slightly_smiling_face:

**Review by johlju — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/97#-:-MeOMA6W27KO3R14eIAE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PlagueHO)

**Pull request merged**
