### PR TITLE
New Task - `Package_Wiki_Content`

### PR DESCRIPTION
**Pull request by dan-hughes**
#### Pull Request (PR) description
Add new task `Package_Wiki_Content` to compress generated docs into an archive.

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [x] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.DocGenerator/144)

### CODE REVIEW

**Comment by dan-hughes** [comment]
@johlju

**Comment by johlju** [comment]
Seems there is a problem with the tests unrelated to this change. Kicked off the tests again just to verify.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.DocGenerator/144#-:-Nz3n_lzDKEWkXFvp4SB:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-hughes)

**Comment by johlju** [comment]
Yes.

Suggest skipping the tests on Linux

https://github.com/dsccommunity/DscResource.DocGenerator/blob/bb3932363f20bb1413e1094369f8ee8a8053f252/tests/unit/private/Get-CompositeResourceParameterState.Tests.ps1#L22

to
```
Describe 'Get-CompositeResourceParameterState' -Skip:$IsLinux {
```

Same for any other tests. I can do it in another PR if you like?

**Comment by dan-hughes** [comment]
> Yes. To much work supporting Linux.
> 
> Suggest skipping the tests on Linux. Change:
> 
> https://github.com/dsccommunity/DscResource.DocGenerator/blob/bb3932363f20bb1413e1094369f8ee8a8053f252/tests/unit/private/Get-CompositeResourceParameterState.Tests.ps1#L22
> 
> to
> 
> ```
> Describe 'Get-CompositeResourceParameterState' -Skip:$IsLinux {
> ```
> 
> Same for any other tests. I can do it in another PR if you like?

Done, Had to use an `if` though as `-Skip` is Pester 5.

**Review by johlju — APPROVED** [review]
Ah, right. Skip is only on It-blocks in Pester 4.

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.DocGenerator/144#-:-Nz41ElcCxor5p3F3q0r:bjyb1us)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-hughes)

**Pull request merged**
