### PR TITLE
[Invoke-Git] Return Object & Change to Public Function

### PR DESCRIPTION
**Pull request by phbits**
# Pull Request

### Pull Request (PR) description
- `Invoke-Git` 
  - Now a public function since `Tasks` can only use public functions.
  - Returns an object allowing caller to take appropriate action.
  - Updated tests.

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Documentation added/updated in README.md.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated.
- [x] Integration tests added/updated (where possible).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/80)

### CODE REVIEW

**Comment by johlju** [comment]
It seems the changes did not work as expected, it failed to publish to the Wiki. See error https://dev.azure.com/dsccommunity/DscResource.DocGenerator/_build/results?buildId=4801&view=logs&j=5d0a9c4e-8741-5118-af45-406a30fe661c&t=bda0b158-a237-516f-c1d0-31339587c5b5&l=146

```
2021-06-19T15:25:33.0578840Z Publishing Wiki content.
2021-06-19T15:25:33.2106611Z ERROR: Exception calling "Start" with "0" argument(s): "No such file or directory"
2021-06-19T15:25:33.2107271Z At /home/vsts/work/1/s/output/DscResource.DocGenerator/0.9.0/DscResource.DocGenerator.psm1:1402 char:13
2021-06-19T15:25:33.2108430Z +         if ($process.Start() -eq $true)
2021-06-19T15:25:33.2108871Z +             ~~~~~~~~~~~~~~~~~~~~~~~~~~
2021-06-19T15:25:33.2151472Z At /home/vsts/work/1/s/source/tasks/Publish_GitHub_Wiki_Content.build.ps1:102 char:1
```

**Comment by johlju** [comment]
Maybe this PR is needed to complete everything? 🙂

**Comment by johlju** [comment]
@phbits I will review this once you rebased this PR. 🙂

**Comment by phbits** [comment]
> 
> 
> @phbits I will review this once you rebased this PR. 🙂

I did the rebase and had to do a force push. After manually resolving conflicts and fixing typos, this PR looks ready.

**Review by johlju — CHANGES_REQUESTED** [review]
Awesome work! Just a few minor comments. :smiley: 

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/80#-:-Md14mgy3SQ7WPGz7yRV:bovlnpz)* status: all files reviewed, 4 unresolved discussions (waiting on @phbits)

___
*[source/Public/Publish-WikiContent.ps1, line 115 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/80#-Md12BEJ0b55UaHtli_c:-Md12BEJ0b55UaHtli_d:b-h03vsa) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/ba135d0f614815c693abe1ba83b7f66e1045157c/source/Public/Publish-WikiContent.ps1#L115)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>             Write-Verbose -Message $script:localizedData.ConfigGlobalGitMessage
>             if ($PSBoundParameters.ContainsKey('GlobalCoreAutoCrLf'))
>             {
>                 $null = Invoke-Git -WorkingDirectory $tempPath.FullName `
>                             -Arguments @( 'config', '--local', 'core.autocrlf', $GlobalCoreAutoCrLf )
>             }
> ```
</details>


This must be run before cloning, since it tells git how to treat linebreaks during clone. 
___
*[tests/unit/public/Publish-WikiContent.Tests.ps1, line 139 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/80#-Md13VLVCaXj6J5w6QwH:-Md13VLVCaXj6J5w6QwI:b-k1rrbz) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/ba135d0f614815c693abe1ba83b7f66e1045157c/tests/unit/public/Publish-WikiContent.Tests.ps1#L139)):*
> ```
>  Context 'When publishing Wiki content' {
> ```

Can we add a new line before this line?
___
*[tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1, line 39 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/80#-Md14FlH4jwVnXppq5R0:-Md14FlH4jwVnXppq5R1:bz00ahw) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/ba135d0f614815c693abe1ba83b7f66e1045157c/tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1#L39)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>         } -ParameterFilter {
>                 $Arguments[0] -eq 'remote' -and
>                 $Arguments[1] -eq 'get-url' -and
>                 $Arguments[2] -eq 'origin'
>             }
> ```
</details>


Indentation looks wrong here.
___
*[tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1, line 116 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/80#-Md14HPE4Zix48aQ_kaD:-Md14HPE4Zix48aQ_kaE:bbxvw1c) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/ba135d0f614815c693abe1ba83b7f66e1045157c/tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1#L116)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>                     $Arguments[0] -eq 'remote' -and
>                     $Arguments[1] -eq 'get-url' -and
>                     $Arguments[2] -eq 'origin'
>                 }
> ```
</details>


Indentation looks wrong here.

**Comment by johlju** [comment]
@phbits you need to rebase again since another PR was merged. 🙂

**Review by phbits — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/80)* status: 4 of 9 files reviewed, 4 unresolved discussions (waiting on @johlju)

___
*[source/Public/Publish-WikiContent.ps1, line 115 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/80#-Md12BEJ0b55UaHtli_c:-Md4LyAU5XnD_psQqtAI:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/ba135d0f614815c693abe1ba83b7f66e1045157c/source/Public/Publish-WikiContent.ps1#L115)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>             Write-Verbose -Message $script:localizedData.ConfigGlobalGitMessage
>             if ($PSBoundParameters.ContainsKey('GlobalCoreAutoCrLf'))
>             {
>                 $null = Invoke-Git -WorkingDirectory $tempPath.FullName `
>                             -Arguments @( 'config', '--local', 'core.autocrlf', $GlobalCoreAutoCrLf )
>             }
> ```

This must be run before cloning, since it tells git how to treat linebreaks during clone. 
</blockquote></details>

Done.
___
*[tests/unit/public/Publish-WikiContent.Tests.ps1, line 139 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/80#-Md13VLVCaXj6J5w6QwH:-Md4LUy97ZLImlP5V-7w:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/ba135d0f614815c693abe1ba83b7f66e1045157c/tests/unit/public/Publish-WikiContent.Tests.ps1#L139)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>  Context 'When publishing Wiki content' {
> ```

Can we add a new line before this line?
</blockquote></details>

Done.
___
*[tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1, line 39 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/80#-Md14FlH4jwVnXppq5R0:-Md4LcIw3Oey_l9sOuVd:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/ba135d0f614815c693abe1ba83b7f66e1045157c/tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1#L39)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>         } -ParameterFilter {
>                 $Arguments[0] -eq 'remote' -and
>                 $Arguments[1] -eq 'get-url' -and
>                 $Arguments[2] -eq 'origin'
>             }
> ```

Indentation looks wrong here.
</blockquote></details>

Done.
___
*[tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1, line 116 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/80#-Md14HPE4Zix48aQ_kaD:-Md4LcqYDfkRm1M5ps_2:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/ba135d0f614815c693abe1ba83b7f66e1045157c/tests/unit/tasks/Publish_GitHub_Wiki_Content.build.Tests.ps1#L116)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>                     $Arguments[0] -eq 'remote' -and
>                     $Arguments[1] -eq 'get-url' -and
>                     $Arguments[2] -eq 'origin'
>                 }
> ```

Indentation looks wrong here.
</blockquote></details>

Done.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/80#-:-Md7X5LL6-7uy05rzvKk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @phbits)

**Pull request merged**
