### PR TITLE
updating tasks to use new sampler functions

### PR DESCRIPTION
**Pull request by gaelcolas**
Fixing the module with the newest prerelease version of Sampler

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/65)

### CODE REVIEW

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/65)* status: all files reviewed, 4 unresolved discussions (waiting on @gaelcolas)

*[a discussion](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/65#-MW85IGD7D8DWxE__b2l:-MW85IGD7D8DWxE__b2m:b-c7amrq) (no related file):*
Shouldn't this PR also remove private and public functions that is no longer needed? Or are they still needed somewhere in this repo?

---
___
*[RequiredModules.psd1, line 19 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/65#-MW830YFCDFuwKDEoZ2b:-MW830YFCDFuwKDEoZ2c:bpuizkr) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/c0a53defd2a9b4572ab468364f274b4aca072c4a/RequiredModules.psd1#L19)):*
> ```
> AllowPrerelease = $true
> ```

Can we switch this to non-prerelease now?
___
*[tests/unit/tasks/Generate_Conceptual_Help.build.Tests.ps1, line 64 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/65#-MW84VMc3Gm4ceLxnqzs:-MW84VMc3Gm4ceLxnqzt:b-rj5vtm) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/c0a53defd2a9b4572ab468364f274b4aca072c4a/tests/unit/tasks/Generate_Conceptual_Help.build.Tests.ps1#L64)):*
> ```
> Join-Path -ChildPath '*'
> ```

Why are we changing this? Then the path can be anything, and we no longer test so that the correct (expected) full path is used. :thinking: 
___
*[tests/unit/tasks/Generate_Conceptual_Help.build.Tests.ps1, line 95 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/65#-MW84m-TCWgMHvShychD:-MW84m-TCWgMHvShychE:b-rj5vtm) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/c0a53defd2a9b4572ab468364f274b4aca072c4a/tests/unit/tasks/Generate_Conceptual_Help.build.Tests.ps1#L95)):*
> ```
> Join-Path -ChildPath '*'
> ```

Why are we changing this? Then the path can be anything, and we no longer test so that the correct (expected) full path is used. :thinking:

**Review by gaelcolas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/65)* status: 2 of 8 files reviewed, 4 unresolved discussions (waiting on @johlju)

*[a discussion](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/65#-MW85IGD7D8DWxE__b2l:-MW8PNkW5vg57pBvk0T_:b-yig3s6) (no related file):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Shouldn't this PR also remove private and public functions that is no longer needed? Or are they still needed somewhere in this repo?
</blockquote></details>

ah you're right, the Get-BuiltModuleVersion. Will do.

---
___
*[RequiredModules.psd1, line 19 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/65#-MW830YFCDFuwKDEoZ2b:-MW8PSMn3N1ulGxJR4-Y:bt1drxg) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/c0a53defd2a9b4572ab468364f274b4aca072c4a/RequiredModules.psd1#L19)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> AllowPrerelease = $true
> ```

Can we switch this to non-prerelease now?
</blockquote></details>

My thinking was that since DscResources.DocGenerator depends on Sampler, it's best to be able to build from the prerelease so that if something happens to a Sampler preview, we can find earlier.
Same goes with Sampler.GitHubTasks.

I'm happy to change back, but I thought that was a good idea.

Also it makes it an example of the syntax.
___
*[tests/unit/tasks/Generate_Conceptual_Help.build.Tests.ps1, line 64 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/65#-MW84VMc3Gm4ceLxnqzs:-MW8kDhe89YVRZV2YfZz:bjzieda) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/c0a53defd2a9b4572ab468364f274b4aca072c4a/tests/unit/tasks/Generate_Conceptual_Help.build.Tests.ps1#L64)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Join-Path -ChildPath '*'
> ```

Why are we changing this? Then the path can be anything, and we no longer test so that the correct (expected) full path is used. :thinking: 
</blockquote></details>

Well, I had some issues initially with making the Integration tests working because of the change to the task, and in the end it did not impact the behaviour.
The only difference is WHEN the wildcard is replaced with the ModuleVersionFolder...
This used to be within the Get-BuiltModuleVersion function of the DscResource.DocGenerator, but now is in the task, using a Get-Item.
The issue I had was with (Get-Item $PathWithWildcard).FullName that returned a System.Object[] so I needed a Cast to string before that.
___
*[tests/unit/tasks/Generate_Conceptual_Help.build.Tests.ps1, line 95 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/65#-MW84m-TCWgMHvShychD:-MW8mJXg31NJ0gdIJWLy:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/c0a53defd2a9b4572ab468364f274b4aca072c4a/tests/unit/tasks/Generate_Conceptual_Help.build.Tests.ps1#L95)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Join-Path -ChildPath '*'
> ```

Why are we changing this? Then the path can be anything, and we no longer test so that the correct (expected) full path is used. :thinking: 
</blockquote></details>

Done.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/65#-:-MW8vO7lArFm44a_k85_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gaelcolas)

___
*[RequiredModules.psd1, line 19 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/65#-MW830YFCDFuwKDEoZ2b:-MW8vFmRBG8KunWoVgIC:bin4sja) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/c0a53defd2a9b4572ab468364f274b4aca072c4a/RequiredModules.psd1#L19)):*
<details><summary><i>Previously, gaelcolas (Gael) wrote…</i></summary><blockquote>

My thinking was that since DscResources.DocGenerator depends on Sampler, it's best to be able to build from the prerelease so that if something happens to a Sampler preview, we can find earlier.
Same goes with Sampler.GitHubTasks.

I'm happy to change back, but I thought that was a good idea.

Also it makes it an example of the syntax.
</blockquote></details>

I'm good with it.

**Pull request merged**
