### PR TITLE
fixes #84 & removes --quiet

### LINKED ISSUE #84: Fails to publish to the Wiki
It seems the latest PR that was merged did not work as expected, it failed to publish to the Wiki when dogfooding itself. It will hopefully be resolved by PR #80.

See error https://dev.azure.com/dsccommunity/DscResource.DocGenerator/_build/results?buildId=4801&view=logs&j=5d0a9c4e-8741-5118-af45-406a30fe661c&t=bda0b158-a237-516f-c1d0-31339587c5b5&l=146

Raw output here (if the link above do not work):
```
2021-06-19T15:25:33.0578840Z Publishing Wiki content.
2021-06-19T15:25:33.2106611Z ERROR: Exception calling "Start" with "0" argument(s): "No such file or directory"
2021-06-19T15:25:33.2107271Z At /home/vsts/work/1/s/output/DscResource.DocGenerator/0.9.0/DscResource.DocGenerator.psm1:1402 char:13
2021-06-19T15:25:33.2108430Z +         if ($process.Start() -eq $true)
2021-06-19T15:25:33.2108871Z +             ~~~~~~~~~~~~~~~~~~~~~~~~~~
2021-06-19T15:25:33.2151472Z At /home/vsts/work/1/s/source/tasks/Publish_GitHub_Wiki_Content.build.ps1:102 char:1
```

_Originally posted by @johlju in https://github.com/dsccommunity/DscResource.DocGenerator/issues/80#issuecomment-864421851_

### PR DESCRIPTION
**Pull request by phbits**
# Pull Request

### Pull Request (PR) description

- Sets `Invoke-Git` `-TimeOut` to milliseconds.
- Removes `--quiet` switch from `git` commands
- Fixes tests

#### This Pull Request (PR) fixes the following issues

- Fixes #84 

#### Task list
- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Documentation added/updated in README.md.
- [x] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated.
- [x] Integration tests added/updated (where possible).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/87)

### CODE REVIEW

**Comment by phbits** [comment]
@johlju Thanks for setting up the debug branch! I'll take a closer look in the next day or two. As you'll notice, the issue was `$TimeOut` needed to be specified in milliseconds. 🤦‍♂️ Also removed all `--quiet` switches  from the git commands allowing the `Invoke-Git` returned object to be populated. Finally, in the last commit, the more specific `Assert` wasn't being triggered which didn't make much sense. I made the "fix" so this PR could be posted and fix publishing. I can take a closer look later if you'd like to go back to the prior technique of having two separate `Assert` statements. Again, wanted to get this posted. Hope that makes sense.

**Comment by johlju** [comment]
Thanks for taking the time to send in fixes! 🙂 I will review this as soon as I have time (hopefully tomorrow).

**Comment by phbits** [comment]
Sounds good.

Did some testing locally and found `$Arguments[2] -eq "*"` would work as expected; calling each `Assert` once. Updated it to `$Arguments[2] -eq $($mockPublishWikiContentParameters.ModuleVersion)"`, just like [17b3cf6](https://github.com/dsccommunity/DscResource.DocGenerator/pull/87/commits/17b3cf6def9710ecd0f2afc4b142e4c376769ebb), and it completed successfully too. Pushed commit with enthusiasm... and Azure Pipelines doesn't like it. 🤔

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/87)* status: all files reviewed, 1 unresolved discussion (waiting on @phbits)

___
*[tests/unit/public/Publish-WikiContent.Tests.ps1, line 227 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/87#-MdfWJFc65_S_0u-CXc1:-MdfWJFc65_S_0u-CXc2:b-dx1w1y) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/852343eb0ba08f8a397b383e97627cb7fcf24f94/tests/unit/public/Publish-WikiContent.Tests.ps1#L227)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>                 Assert-MockCalled -CommandName Invoke-Git -ParameterFilter {
>                     $Arguments[0] -eq 'push' -and
>                     $Arguments[1] -eq 'origin'
>                 } -Exactly -Times 1 -Scope It
> ```
</details>


On this assert I think we need to add `$Arguments[2] -notlike $mockPublishWikiContentParameters.ModuleVersion`, or `$null -eq $Arguments[2]`, or `$Arguments.Count -eq 2`. Not sure which one is best, maybe the last one?

Otherwise it returns two hits for these two calls:
https://github.com/dsccommunity/DscResource.DocGenerator/blob/852343eb0ba08f8a397b383e97627cb7fcf24f94/source/Public/Publish-WikiContent.ps1#L164-L168

See error:
```
Executing script D:\a\1\s\tests\unit\public\Publish-WikiContent.Tests.ps1

  Describing Publish-WikiContent

    Context When cloning Wiki content fails
      [+] Should not throw an exception and call the expected mocks 227ms

    Context When publishing Wiki content
      [-] Should not throw an exception and call the expected mocks 817ms
        Expected Invoke-Git in module DscResource.DocGenerator to be called 1 times exactly but was called 2 times
        227:                 Assert-MockCalled -CommandName Invoke-Git -ParameterFilter {
        at <ScriptBlock>, D:\a\1\s\tests\unit\public\Publish-WikiContent.Tests.ps1: line 227
```
https://dev.azure.com/dsccommunity/DscResource.DocGenerator/_build/results?buildId=4877&view=logs&j=6e96c990-2aec-5c19-de23-7935a8ed5902&t=2c7b089f-5c8d-539f-194a-4eccb6cac1fd&l=995

**Review by phbits — COMMENTED** [review]
Thanks for the suggestions! Found one that worked. :partying_face: 

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/87#-:-Mdx3OCo8YyrcS2DUAjB:b-h3og9z)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @johlju and @phbits)

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/87#-:-Mdx4aSj5bvN6gSrpCh7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @phbits)

**Pull request merged**
