### PR TITLE
`Get-ClassResourceProperty` - Check for prefixed and non-prefixed class names

### LINKED ISSUE #132: Issue generating a class
Creating this DSC Resource class makes the DocGenerator fail:

```PowerShell
using namespace System.Management.Automation

<#
    .SYNOPSIS
        The `ChocolateyPackage` DSC resource is used to install or remove chocolatey
        packages.
    .DESCRIPTION
        The ChocolateyPackage DSC Resource helps with chocolatey package management.
    .PARAMETER Name
        The exact name of the ChocolateyPackage to set in the desired state.
    .PARAMETER Version
        The version of the package to install. If not set, it will only ensure the package
        is present/absent.
        If set to latest, it will always make sure the latest version available on the source is
        the one installed.
        If set to a version it will try to compare and make sure the installed version is greater
        or equal than the one desired.
    .PARAMETER ChocolateyOptions
        Chocolatey parameters as per the Install or Update chocolateyPackage commands.
    .PARAMETER UpdateOnly
        Only update the package if present.
        When absent do not attempt to install.
    .PARAMETER Reasons
        Reason for compliance or non-compliance returned by the Get method.
    .EXAMPLE
        Invoke-DscResource -ModuleName Chocolatey -Name ChocolateyPackage -Method Get -Property @{
            Ensure         = 'present'
            Name           = 'localhost'
            UpdateOnly     = $true
        }

        This example shows how to call the resource using Invoke-DscResource.
#>
[DscResource(RunAsCredential = 'Optional')]
class ChocolateyPackage
{
    [DscProperty(Mandatory)]
    [Ensure] $Ensure = 'Present'

    [DscProperty(Key)]
    [String] $Name

    [DscProperty()]
    [String] $Version

    [DscProperty()]
    [hashtable] $ChocolateyOptions

    [DscProperty()]
    [PSCredential] $Credential

    [DscProperty(NotConfigurable)]
    [bool] $UpdateOnly

    [DscProperty(NotConfigurable)]
    [ChocolateyReason[]] $Reasons

    [ChocolateyPackage] Get()
    {
        $currentState = [ChocolateyPackage]::new()
        $currentState.Name = $this.Name
        $localPackage = Get-ChocolateyPackage -LocalOnly -Name $this.Name -Exact

        if ($null -eq $localPackage)
        {
            Write-Debug -Message ('Local Package ''{0}'' not found.' -f $this.Name)
            $currentState.Ensure = [Ensure]::Absent
        }
        else
        {
            Write-Debug -Message ('Local Package found: {0}' -f ($localPackage | ConvertTo-Json))
            $currentState.Ensure = [ensure]::Present
            $currentState.Version = $localPackage.Version
        }

        if ($this.Ensure -eq 'Absent' -and $currentState.Ensure -eq $this.Ensure)
        {
            Write-Debug -Message ('The package named ''{0}'' is absent as expected.' -f $this.Name)
            $currentState.Reasons += @{
                Code   = ('ChocolateyPackage:ChocolateyPackage:Compliant')
                Phrase = ('The Package ''{0}'' is not installed as desired.' -f $currentState.Name)
            }
        }
        elseif ([string]::IsNullOrEmpty($this.Version) -and $currentState.Ensure -eq $this.Ensure)
        {
            Write-Debug -Message ('The package named ''{0}'' is present as expected. No version required.' -f $this.Name)
            $currentState.Reasons += @{
                Code   = ('ChocolateyPackage:ChocolateyPackage:Compliant')
                Phrase = ('The Package ''{0}'' is installed (with version ''{1}'').' -f $currentState.Name, $currentState.Version)
            }
        }
        elseif (-not [string]::IsNullOrEmpty($this.Version) -and $this.Version -eq $localPackage.Version -and $currentState.Ensure -eq $this.Ensure)
        {
            Write-Debug -Message ('The package named ''{0}'' is present with expected version.' -f $this.Name)
            $currentState.Reasons += @{
                Code   = ('ChocolateyPackage:ChocolateyPackage:Compliant')
                Phrase = ('The Package ''{0}'' is installed with expected version ''{1}''.' -f $currentState.Name, $currentState.Version)
            }
        }
        elseif ($currentState.Ensure -ne $this.Ensure)
        {
            if ($this.Ensure -eq 'Absent')
            {
                $currentState.Reasons += @{
                    Code   = ('ChocolateyPackage:ChocolateyPackage:ShouldNotBeInstalled')
                    Phrase = ('The Package ''{0}'' is installed with version ''{1}'' but is NOT expected to be present.' -f $currentState.Name, $currentState.Version)
                }
            }
            else
            {
                $currentState.Reasons += @{
                    Code   = ('ChocolateyPackage:ChocolateyPackage:ShouldBeInstalled')
                    Phrase = ('The Package ''{0}'' is not installed but is expected to be present.' -f $currentState.Name)
                }
            }
        }
        else
        {
            Write-Debug -Message ('The package named ''{0}'' is ''Present'' with version ''{1}'' while we expect version ''{2}''.' -f $this.Name, $currentState.Version,$this.Version)
            if ('latest' -eq $this.Version)
            {
                Write-Debug -Message ('  Grabbing the latest version of ''{0}'' from source.' -f $this.Name)
                $searchVersionParam = @{
                    Exact = $true
                    Name  = $this.Name
                }

                if ($this.ChocolateyOptions -and $this.ChocolateyOptions.ContainsKey('source'))
                {
                    Write-Debug -Message ('  Searching in specified source ''{0}''.' -f $this.ChocolateyOptions['source'])
                    $searchVersionParam['source'] = $this.ChocolateyOptions['source']
                }

                Write-Debug -Message ('  Searching with ''Get-ChocolateyPackage'' and parameters {0}' -f ($searchVersionParam | ConvertTo-Json -Depth 3))
                $refVersionPackage = Get-ChocolateyPackage @searchVersionParam

                if ($null -eq $refVersionPackage)
                {
                    Write-Debug -Message ('The package ''{0}'' could not be found on the source repository.' -f $this.Name)
                    $refVersion = $null
                    $currentState.Reasons += @{
                        Code   = ('ChocolateyPackage:ChocolateyPackage:LatestPackageNotFound')
                        Phrase = ('The Package ''{0}'' is installed with version ''{1}'' but couldn''t be found on the source.' -f $currentState.Name, $currentState.Version, $this.Version)
                    }
                }
                else
                {
                    $refVersion = $refVersionPackage.Version
                    Write-Debug -Message ('Latest version for ''{0}'' found in source is ''{1}''.' -f $this.Name, $refVersion)
                }
            }
            else
            {
                $refVersion = $this.Version
            }

            if ([string]::IsNullOrEmpty($refVersion))
            {
                # No need to check for version because the 'LatestPackageNotFound' on source...
            }
            elseif ((Compare-SemVerVersion -ReferenceVersion $refVersion -DifferenceVersion $currentState.version) -in @('=', '<'))
            {
                $currentState.Reasons += @{
                    Code   = ('ChocolateyPackage:ChocolateyPackage:Compliant')
                    Phrase = ('The Package ''{0}'' is installed with version ''{1}'' higher or equal than the expected ''{2}'' (''{3}'').' -f $currentState.Name, $currentState.Version, $this.Version, $refVersion)
                }
            }
            else
            {
                $currentState.Reasons += @{
                    Code   = ('ChocolateyPackage:ChocolateyPackage:BelowExpectedVersion')
                    Phrase = ('The Package ''{0}'' is installed with version ''{1}'' Lower than the expected ''{2}''.' -f $currentState.Name, $currentState.Version, $this.Version)
                }
            }
        }

        return $currentState
    }

    [bool] Test()
    {
        $currentState = $this.Get()

        if ($currentState.Reasons.Code.Where({$_ -in @('BelowExpectedVersion','ShouldBeInstalled','ShouldNotBeInstalled','')}))
        {
            return $false
        }
        else
        {
            return $true
        }
    }

    [void] Set()
    {
        [ChocolateyPackage] $currentState = $this.Get()
        $chocoCommand = Get-Command 'Install-ChocolateyPackage'
        [hashtable] $chocoCommandParams = @{
            Name        = $this.Name
            Confirm     = $false
            ErrorAction = 'Stop'
        }

        switch -Regex ($currentState.Reasons.Code)
        {
            'BelowExpectedVersion$'
            {
                Write-Debug -Message ('Upgrading package ''{0}'' to version ''{1}''.' -f $this.Name, $this.Version)
                $chocoCommand = Get-Command -Name 'Update-ChocolateyPackage' -Module 'Chocolatey'
            }

            'ShouldBeInstalled$'
            {
                $chocoCommand = Get-Command -Name 'Install-ChocolateyPackage' -Module 'Chocolatey'

                if ('latest' -eq $this.Version -or [string]::IsNullOrEmpty($this.Version))
                {
                    Write-Debug -Message ('Installing the ''latest'' version of ''{0}'' from the configured or specified source.' -f $this.Name)
                }
                else
                {
                    Write-Debug -Message ('Installing package ''{0}'' to version ''{1}''.' -f $this.Name, $this.Version)
                    $chocoCommandParams['Version'] = $this.Version
                }
            }

            'ShouldNotBeInstalled$'
            {
                $chocoCommand = Get-Command -Name 'Uninstall-ChocolateyPackage' -Module 'Chocolatey'
                $chocoCommandParams['Force'] = $true
            }
        }

        if ($this.UpdateOnly -and $chocoCommand.Name -eq 'Install-ChocolateyPackage')
        {
            Write-Verbose -Message ('Skipping install of ''{0}'' because ''UpdateOnly'' is set.' -f $this.Name)
            return
        }

        if ($this.Credential)
        {
            $chocoCommandParams['Credential'] = $this.Credential
        }

        $this.ChocolateyOptions.keys.Where{$_ -notin $chocoCommandParams.Keys}.Foreach{
            if ($chocoCommand.Parameters.Keys -contains $_)
            {
                if ($this.ChocolateyOptions[$_] -in @('True','False'))
                {
                    $chocoCommandParams[$_] = [bool]::Parse($this.ChocolateyOptions[$_])
                }
                else
                {
                    $chocoCommandParams[$_] = $this.ChocolateyOptions[$_]
                }
            }
            else
            {
                Write-Verbose -Message ('  Ignoring parameter ''{0}''. Not suported by ''{1}''.' -f $_, $chocoCommand.Name)
            }
        }

        Write-Verbose -Message ('  Calling ''{0}'' with parameters {1}.' -f $chocoCommand.Name,($chocoCommandParams | ConvertTo-Json -Depth 3))
        &$($chocoCommand.Name) @ChocoCommandParams
    }
}
```

And error output for the Generate Wiki Content:
```text
===============================================================================
                        GENERATE WIKI CONTENT
This task generates wiki documentation for the DSC resources.
-------------------------------------------------------------------------------
  /build/Generate_Wiki_Content
  C:\src\Chocolatey\output\RequiredModules\DscResource.DocGenerator\0.11.2\tasks\Generate_Wiki_Content.build.ps1:84

        Project Name               = 'Chocolatey'
        Source Path                = 'C:\src\Chocolatey\source'
        Output Directory           = 'C:\src\Chocolatey\output'
        Release Notes path         = 'C:\src\Chocolatey\output\ReleaseNotes.md'
        Built Module Subdirectory  = 'C:\src\Chocolatey\output\module'
        Module Manifest Path (src) = 'C:\src\Chocolatey\source\Chocolatey.psd1'
        Versioned Output Directory = 'True'
        Built Module Manifest      = 'C:\src\Chocolatey\output\module\Chocolatey\0.2.0\Chocolatey.psd1'
        Built Module Base          = 'C:\src\Chocolatey\output\module\Chocolatey\0.2.0'
        Module Version             = '0.2.0-dscclass0001'
        Module Version Folder      = '0.2.0'
        Pre-release Tag            = 'dscclass0001'
        Built Module Root Script   = 'C:\src\Chocolatey\output\module\Chocolatey\0.2.0\Chocolatey.psm1'
        PSModulePath               = 'C:\src\Chocolatey\output\module;
                                      C:\src\Chocolatey\output\RequiredModules;
                                      C:\Program Files\WindowsPowerShell\Modules;
                                      C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;'

        Wiki Output Path             = C:\src\Chocolatey\output\WikiContent
Generating Wiki content for all DSC resources based on source and built module.
WARNING: No README.md description file found for 'ChocolateyFeature', skipping.
WARNING: No README.md description file found for 'ChocolateyPin', skipping.
WARNING: No README.md description file found for 'ChocolateySetting', skipping.
WARNING: No README.md description file found for 'ChocolateySoftware', skipping.
WARNING: No README.md description file found for 'ChocolateySource', skipping.
ERROR: Cannot bind argument to parameter 'Property' because it is null.
At C:\src\Chocolatey\output\RequiredModules\DscResource.DocGenerator\0.11.2\DscResource.DocGenerator.psm1:3299 char:5
+     New-DscClassResourceWikiPage @PSBoundParameters
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At C:\src\Chocolatey\output\RequiredModules\DscResource.DocGenerator\0.11.2\tasks\Generate_Wiki_Content.build.ps1:84 char:1
+ task Generate_Wiki_Content {
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Build FAILED. 9 tasks, 1 errors, 0 warnings 00:00:02.4016381
New-DscClassResourceWikiPage : Cannot bind argument to parameter 'Property' because it is null.
At C:\src\Chocolatey\output\RequiredModules\DscResource.DocGenerator\0.11.2\DscResource.DocGenerator.psm1:3299 char:5
+     New-DscClassResourceWikiPage @PSBoundParameters
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-DscClassResourceWikiPage], ParameterBindingValidationException
```

### PR DESCRIPTION
**Pull request by dan-hughes**
#### Pull Request (PR) description
Update `Get-ClassResourceProperty` to allow use of prefixed and non-prefixed class names.

#### This Pull Request (PR) fixes the following issues
- Fixes #132 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [ ] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.DocGenerator/152)

### CODE REVIEW

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.DocGenerator/152)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-hughes)

___
*[`source/Private/Get-ClassResourceProperty.ps1` line 63 at r2](https://reviewable.io/reviews/dsccommunity/DscResource.DocGenerator/152#-O4AK0Iv67unu2CcbhYN:-O4AJs_Y1JaipqLtOD1O:bfiv6lm) ([raw file](https://github.com/dsccommunity/DscResource.DocGenerator/blob/68d1827cea47d68691aac0d2ea05a26bc4903b8c/source/Private/Get-ClassResourceProperty.ps1#L63)):*
> ```PowerShell
>             }
> 
>             if ($classExists) { break }
> ```

Can we move the `break` inside the previious if-block, then we dont need this if-block at all?

**Comment by johlju** [comment]
Thanks for fixing this!

**Review by dan-hughes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.DocGenerator/152)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @johlju)

___
*[`source/Private/Get-ClassResourceProperty.ps1` line 63 at r2](https://reviewable.io/reviews/dsccommunity/DscResource.DocGenerator/152#-O4AK0Iv67unu2CcbhYN:-O4AM_ytAXKkNsk0be8j:b-896fix) ([raw file](https://github.com/dsccommunity/DscResource.DocGenerator/blob/68d1827cea47d68691aac0d2ea05a26bc4903b8c/source/Private/Get-ClassResourceProperty.ps1#L63)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Can we move the `break` inside the previious if-block, then we dont need this if-block at all?
</blockquote></details>

Done.

**Comment by dan-hughes** [comment]
@johlju, over to you.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.DocGenerator/152#-:-O4Bxhf4-fVpSatTwXGB:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-hughes)

**Pull request merged**
