### PR TITLE
Fixing Wiki, ASCII encoding parameter values (Issue #45)

### LINKED ISSUE #45: Set-WikiModuleVersion: Invalid `Encoding` parameter value
#### Details of the scenario you tried and the problem that is occurring
This module gets used as part of the `SqlServerDsc` build (and likely others), and raises the following error/exception off an initial run from a freshly cloned repository:

`Set-WikiModuleVersion : Cannot validate argument on parameter 'Encoding'. The argument "System.Text.ASCIIEncoding" does not belong to the set "unknown,string,unicode,bigendianunicode,utf8,utf7,utf32,ascii,default,oem" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the
command again.`

#### Steps to reproduce the problem

* Take a fresh, local clone of the `SqlServerDsc` repository
* Run `.\build.ps1 -ResolveDependency` from within the local repository/directory
* Throws error when generating the wiki

#### Expected behavior

I'd presume this shouldn't error and the Wiki would be generated/updated successfully.

#### Current behavior

Error/Exception is thrown: 

`Set-WikiModuleVersion : Cannot validate argument on parameter 'Encoding'. The argument "System.Text.ASCIIEncoding" does not belong to the set "unknown,string,unicode,bigendianunicode,utf8,utf7,utf32,ascii,default,oem" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the
command again.`

#### Suggested solution to the issue

Update [`Set-WikiModuleVersion.ps1`](https://github.com/dsccommunity/DscResource.DocGenerator/blob/master/source/Public/Set-WikiModuleVersion.ps1) to change ...

```PowerShell
Out-File -InputObject $markdownContent -FilePath $Path -Encoding ([System.Text.Encoding]::ASCII) -NoNewline
```

..to...

```PowerShell
Out-File -InputObject $markdownContent -FilePath $Path -Encoding 'ascii' -NoNewline
```

Making this change seemed to remove the error when tried locally.

#### The operating system the target node is running
OsName               : Microsoft Windows 10 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2004
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-GB
OsMuiLanguages       : {en-GB}

#### Version and build of PowerShell the target node is running
PSVersion                      5.1.19041.610
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.610
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the module that was used
0.7.1

### PR DESCRIPTION
**Pull request by SphenicPaul**
# Pull Request

#### This Pull Request (PR) fixes the following issues
Fixes #45

#### Task list
- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated.
- [ ] Integration tests added/updated (where possible).
- [ ] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/46)

### CODE REVIEW

**Comment by SphenicPaul** [comment]
Note that the failing tests seem to all be related to the build tasks and also failed locally for me, prior to any changes. For example...

* `Task 'Generate_Conceptual_Help': Cannot add tasks.`
* `Task 'Generate_Wiki_Content': Cannot add tasks.`
* `Task 'Publish_Gihub_Wiki_Content': Cannot add tasks.`

I'm not clear enough on this module's build is expected/designed to work (and it looks a little new/unstable so not wanting to start digging into this as there might be a quick/easy answer/fix) so I'll leave my changes in this PR for when those are resolved.

Shout if you've any questions

**Comment by johlju** [comment]
Closing an reopening to kick off the tests again.

**Comment by johlju** [comment]
I'm not sure what is going on. The test that fails should just dot-source using the alias that points to the build task script. It is meant to verify that the alias points to a script that parse correctly 🤔  It worked last time I worked on this but something might have changed. I need to dig into it to understand why it happening, but it is gonna take a while.

**Comment by johlju** [comment]
I will try to look into this during next week so we can get this merged.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/46#-:-MRFb6ww6JotwyqGROJi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SphenicPaul)

**Comment by johlju** [comment]
Couldn't let it go, so I fixed the problem. Will merge this shortly! Thank you @SphenicPaul!  😃

**Pull request merged**
