### PR TITLE
[Invoke-Git] Convert to use System.Diagnostics.Process

### PR DESCRIPTION
**Pull request by phbits**
### Pull Request (PR) description
In a prior project, I came across AuditPolicyDsc which uses `System.Diagnostics.Process` to launch `auditpol.exe` (ref: [AuditPolicyResourceHelper.psm1](https://github.com/dsccommunity/AuditPolicyDsc/blob/dev/DSCResources/AuditPolicyResourceHelper/AuditPolicyResourceHelper.psm1)) as it provides more flexibility with handling error conditions. Thus converting this module is the first step toward improving error handling as mentioned in Issue #75.

I liked the readability of `Publish-WikiContent` and why I opted to pass the WorkingDirectory as the first argument. This leads to another benefit of not having to use `Set-Location` and similar commands.

#### This Pull Request (PR) fixes the following issues
- None

#### Task list
- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Documentation added/updated in README.md.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated.
- [x] Integration tests added/updated (where possible).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76)

### CODE REVIEW

**Review by phbits — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @phbits)

___
*[source/Private/Invoke-Git.ps1, line 45 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-Ma9fANH-vVZIBsXCx6B:-Ma9fANH-vVZIBsXCx6C:b6vzmti) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/db4f536958e84a3c6932918c6f0b259e6fefce12/source/Private/Invoke-Git.ps1#L45)):*
> ```PowerShell
>         if ($LASTEXITCODE -gt 1)
>         {
>             throw $LASTEXITCODE
> ```

I removed this `throw` so `Publish-WikiContent` can take appropriate action based on the returned `ExitCode`. Not entirely evident by this PR but will be used later.

**Review by phbits — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @phbits)

___
*[source/en-US/DscResource.DocGenerator.strings.psd1, line 19 at r3](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-MaFUha86v5GfyQlqdCJ:-MaFUha9C3aT81g1G0og:b-xokgct) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/875c5a6647cded13f4bb8401b85ecf030bb30ce0/source/en-US/DscResource.DocGenerator.strings.psd1#L19)):*
> ```PowerShell
>     PushUpdatedRepoMessage              = Pushing the updated Repository to the Git Wiki.
>     PublishWikiContentCompleteMessage   = Publish Wiki Content complete.
>     UpdateWikiCommitMessage             = "Updating Wiki with the content for module version '{0}'."
> ```

While testing PAT permissions for the SAMPLER gist, I encountered the following error and would like to include the fix into this PR.

```powershell
WARNING: Unexpected return code '1' from the following Git command.
WARNING:   PWD: C:\Users\username\AppData\Local\Temp\rccb2tj1.pap
WARNING:   git commit --message Updating Wiki with the content for module version '0.0.0.5'. --quiet
WARNING:   ERROR: error: pathspec 'Wiki' did not match any file(s) known to git
error: pathspec 'with' did not match any file(s) known to git
error: pathspec 'the' did not match any file(s) known to git
error: pathspec 'content' did not match any file(s) known to git
error: pathspec 'for' did not match any file(s) known to git
error: pathspec 'module' did not match any file(s) known to git
error: pathspec 'version' did not match any file(s) known to git
error: pathspec ''0.0.0.5'.' did not match any file(s) known to git
WARNING: There are no changes to the documentation to commit and push to the Wiki.
```

**Comment by johlju** [comment]
I will review this a day when I have more time. 😃 But a quick view it looks like a good addition!

**Review by johlju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @phbits)

___
*[source/en-US/DscResource.DocGenerator.strings.psd1, line 19 at r3](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-MaFUha86v5GfyQlqdCJ:-MahUpGb-WCg2Ij2cai_:b1dbh4q) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/875c5a6647cded13f4bb8401b85ecf030bb30ce0/source/en-US/DscResource.DocGenerator.strings.psd1#L19)):*
<details><summary><i>Previously, phbits wrote…</i></summary><blockquote>

While testing PAT permissions for the SAMPLER gist, I encountered the following error and would like to include the fix into this PR.

```powershell
WARNING: Unexpected return code '1' from the following Git command.
WARNING:   PWD: C:\Users\username\AppData\Local\Temp\rccb2tj1.pap
WARNING:   git commit --message Updating Wiki with the content for module version '0.0.0.5'. --quiet
WARNING:   ERROR: error: pathspec 'Wiki' did not match any file(s) known to git
error: pathspec 'with' did not match any file(s) known to git
error: pathspec 'the' did not match any file(s) known to git
error: pathspec 'content' did not match any file(s) known to git
error: pathspec 'for' did not match any file(s) known to git
error: pathspec 'module' did not match any file(s) known to git
error: pathspec 'version' did not match any file(s) known to git
error: pathspec ''0.0.0.5'.' did not match any file(s) known to git
WARNING: There are no changes to the documentation to commit and push to the Wiki.
```
</blockquote></details>

Can we add those double-quotes in the code instead? Otherwise I'm afraid they are removed by someone else thinking it is a typo. :slightly_smiling_face:

**Comment by phbits** [comment]
Found tests in the following are failing and will fix in the next day or two.

`DscResource.DocGenerator\tests\unit\public\Publish-WikiContent.Tests.ps1`

**Comment by johlju** [comment]
I will try to get to this one this weekend.

**Comment by phbits** [comment]
> I will try to get to this one this weekend.

Before looking into this PR, I'd like to run something past you. There's another `git` call in this module:

```powershell
# tasks/Publish_GitHub_Wiki_Content.build.ps1:170
$remoteURL = git remote get-url origin
```

If `Invoke-Git` is modified to return an object, it could be reused for the above instance and any future `git` uses.
```powershell
return @{
    ExitCode       = $process.ExitCode
    StandardOutput = $process.StandardOutput.ReadToEnd()
    StandardError  = $process.StandardError.ReadToEnd()
}
```

Would you be interested in taking this approach? Perhaps something entirely different?

**Comment by johlju** [comment]
If we have a private function `Invoke-Git` that calls `git` then I think all calls should use the same function. 🙂

**Review by johlju — CHANGES_REQUESTED** [review]
Other than improving error handling - will this change improve anything else for the tasks? :thinking: Is there a problem that this change will help improve (eventually)? 

> Reviewed 2 of 6 files at r1, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-:-MbdzOsg4hnsq30I4jHp:b3jq21c)* status: 3 of 6 files reviewed, 13 unresolved discussions (waiting on @phbits)

___
*[source/Private/Invoke-Git.ps1, line 45 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-Ma9fANH-vVZIBsXCx6B:-Mbdy4Er5H5f5_k-Dbyh:bl9hg6h) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/db4f536958e84a3c6932918c6f0b259e6fefce12/source/Private/Invoke-Git.ps1#L45)):*
<details><summary><i>Previously, phbits wrote…</i></summary><blockquote>

I removed this `throw` so `Publish-WikiContent` can take appropriate action based on the returned `ExitCode`. Not entirely evident by this PR but will be used later.
</blockquote></details>

I think by default this function should throw on error to stop the pipeline if git returns an error. If there should be more processing instead of throwing we can add a parameter `PassThru` that will return an object for more processing. Then a specific call can opt-in to not throw.
___
*[source/Private/Invoke-Git.ps1, line 24 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-MbdtqBMDkkKMTfFClb4:-MbdtqBMDkkKMTfFClb5:b-mm7gz3) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/517da028a74133afbabad50a336a7b3ef065f50a/source/Private/Invoke-Git.ps1#L24)):*
> ```
> $workingDirectory = $Arguments[0]
> ```

We should add a parameter `WorkingDirectory`. Since the function is not exported public it is not necessary to use positional parameters since we should use named parameters to follow style guideline. I see now that this function has not followed the style guideline. :)

So the call to Invoke-Git should look like this throughout:

```
Invoke-Git -WorkingDirectory 'MyFolder' -Arguments @('config', '--global', 'core.autocrlf', 'true')
```
___
*[source/Private/Invoke-Git.ps1, line 28 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-Mbdv_5e8Ns0YXGP-pbg:-Mbdv_5f0ETC2eoLlSA9:b6ikxsf) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/517da028a74133afbabad50a336a7b3ef065f50a/source/Private/Invoke-Git.ps1#L28)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     for ($i=1; $i -lt $Arguments.Length; $i++)
>     {
>         [string[]] $cmdArguments += $Arguments[$i]
>     }
> ```
</details>


This should not be needed if we add parameter in previous comment.
___
*[source/Private/Invoke-Git.ps1, line 43 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-Mbe-E7WEKXOQtRHRNIc:-Mbe-E7WEKXOQtRHRNId:b-t3ae22) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/517da028a74133afbabad50a336a7b3ef065f50a/source/Private/Invoke-Git.ps1#L43)):*
> ```
> New-Object System.Diagnostics.Process
> ```

We should use named parameters, e.g. `New-Object -TypeName 'System.Diagnostics.Process'`.
___
*[source/Private/Invoke-Git.ps1, line 56 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-MbdvsZC2NtimOFcbjNV:-MbdvsZC2NtimOFcbjNW:b-10j6qc) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/517da028a74133afbabad50a336a7b3ef065f50a/source/Private/Invoke-Git.ps1#L56)):*
> ```
>  -1 specifies an infinite wait.
> ```

I see a potential that this will keep a build worker running unnecessary long if there is an error. We should add a parameter Timeout with a default value for this instead. Default value can be 120 seconds, it should be sufficient to do most Git work. 

If that is not enough time, then another PR can add the possibility to change the value through the build configuration.
___
*[source/Private/Invoke-Git.ps1, line 70 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-MbdzwzhEN2mF3bLZG-6:-MbdzwzhEN2mF3bLZG-7:b-dicafo) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/517da028a74133afbabad50a336a7b3ef065f50a/source/Private/Invoke-Git.ps1#L70)):*
> ```
>                     Write-Warning -Message "  PWD: $workingDirectory"
>                     Write-Warning -Message "  git $argumentsJoined"
> ```

Can we add these to the localized string warning message above instead of having separate entries. Though, these looks like more as `Write-Debug` messages?
___
*[source/Private/Invoke-Git.ps1, line 72 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-Mbe-h2pAMO-oZiP9rbQ:-Mbe-h2pAMO-oZiP9rbR:bfk0pd1) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/517da028a74133afbabad50a336a7b3ef065f50a/source/Private/Invoke-Git.ps1#L72)):*
> ```
> [string]
> ```

We should use full name `[System.String]`. Same on the line below too.
___
*[source/Private/Invoke-Git.ps1, line 77 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-Mbe-twP6AC_ER76IBSF:-Mbe-twP6AC_ER76IBSG:btwtn70) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/517da028a74133afbabad50a336a7b3ef065f50a/source/Private/Invoke-Git.ps1#L77)):*
> ```
>  Write-Warning -Message "  OUTPUT: $invokeGitOutput"
> ```

What are your thoughts here? Why are we writing the standard output from git as a warning? 
___
*[source/Private/Invoke-Git.ps1, line 79 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-Mbe0KrRDPmWuEu7w6C1:-Mbe0KrRDPmWuEu7w6C2:b-jxqbut) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/517da028a74133afbabad50a336a7b3ef065f50a/source/Private/Invoke-Git.ps1#L79)):*
> ```
> if ([System.String]::IsNullOrWhiteSpace($invokeGitError) -eq $false)
> ```

We should add a new line before this line.
___
*[source/Private/Invoke-Git.ps1, line 87 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-Mbe0cjr-69nqIJtSVM3:-Mbe0cjr-69nqIJtSVM4:b-6kzi00) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/517da028a74133afbabad50a336a7b3ef065f50a/source/Private/Invoke-Git.ps1#L87)):*
> ```
> catch {
> ```

We should have open brace on a separate line.
___
*[source/Private/Invoke-Git.ps1, line 90 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-Mbe0YU8DOv4O7cL7iET:-Mbe0YU8DOv4O7cL7iEU:b-7cqqbx) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/517da028a74133afbabad50a336a7b3ef065f50a/source/Private/Invoke-Git.ps1#L90)):*
> ```
>         $e = $_
>         Write-Error -Message $e.Exception.Message
> ```

It should be enough to do `throw $_`
___
*[source/Private/Invoke-Git.ps1, line 92 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-Mbe0hKkEEhC1LJdlPdl:-Mbe0hKkEEhC1LJdlPdm:b-efoj8o) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/517da028a74133afbabad50a336a7b3ef065f50a/source/Private/Invoke-Git.ps1#L92)):*
> ```
> finally {
> ```

We should have open brace on a separate line.
___
*[source/Private/Invoke-Git.ps1, line 95 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-Mbe0zgB503BWf7BzF44:-Mbe0zgB503BWf7BzF45:b-y3el4s) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/517da028a74133afbabad50a336a7b3ef065f50a/source/Private/Invoke-Git.ps1#L95)):*
> ```
>         $exitCode = $process.ExitCode
>         $process.Dispose()
> ```

Maybe we should check that `$process` is not null here if for some reason the `New-Object`failed?

**Comment by phbits** [comment]
> 
> 
> If we have a private function `Invoke-Git` that calls `git` then I think all calls should use the same function. 🙂

Sounds good. 🙂 This approach will be a significant change from this PR. Would you prefer to have it submitted separately?

**Comment by johlju** [comment]
Yes do it separately in another PR so it is easier to review.  :)

**Review by phbits — COMMENTED** [review]
Ok. Thanks for the feedback here. I've incorporated it into the new branch.

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-:-MbhOr9wEJ3XkNGFFxCr:b-zemgui)* status: 3 of 6 files reviewed, 13 unresolved discussions (waiting on @johlju and @phbits)

___
*[source/Private/Invoke-Git.ps1, line 45 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-Ma9fANH-vVZIBsXCx6B:-Mbh7bgv7I2jNrwW9LdL:b-7dqmwh) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/db4f536958e84a3c6932918c6f0b259e6fefce12/source/Private/Invoke-Git.ps1#L45)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

I think by default this function should throw on error to stop the pipeline if git returns an error. If there should be more processing instead of throwing we can add a parameter `PassThru` that will return an object for more processing. Then a specific call can opt-in to not throw.
</blockquote></details>

Agreed. Now that an object is being returned, if there's an error it will `throw`. 
___
*[source/Private/Invoke-Git.ps1, line 24 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-MbdtqBMDkkKMTfFClb4:-Mbh6A2RDp9ZxJMxQLM1:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/517da028a74133afbabad50a336a7b3ef065f50a/source/Private/Invoke-Git.ps1#L24)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $workingDirectory = $Arguments[0]
> ```

We should add a parameter `WorkingDirectory`. Since the function is not exported public it is not necessary to use positional parameters since we should use named parameters to follow style guideline. I see now that this function has not followed the style guideline. :)

So the call to Invoke-Git should look like this throughout:

```
Invoke-Git -WorkingDirectory 'MyFolder' -Arguments @('config', '--global', 'core.autocrlf', 'true')
```
</blockquote></details>

Done.
___
*[source/Private/Invoke-Git.ps1, line 43 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-Mbe-E7WEKXOQtRHRNIc:-Mbh6Ai19PHl3HcGxQj0:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/517da028a74133afbabad50a336a7b3ef065f50a/source/Private/Invoke-Git.ps1#L43)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> New-Object System.Diagnostics.Process
> ```

We should use named parameters, e.g. `New-Object -TypeName 'System.Diagnostics.Process'`.
</blockquote></details>

Done.
___
*[source/Private/Invoke-Git.ps1, line 56 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-MbdvsZC2NtimOFcbjNV:-Mbh6Fkc2drWu8EMhsSp:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/517da028a74133afbabad50a336a7b3ef065f50a/source/Private/Invoke-Git.ps1#L56)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>  -1 specifies an infinite wait.
> ```

I see a potential that this will keep a build worker running unnecessary long if there is an error. We should add a parameter Timeout with a default value for this instead. Default value can be 120 seconds, it should be sufficient to do most Git work. 

If that is not enough time, then another PR can add the possibility to change the value through the build configuration.
</blockquote></details>

Done.
___
*[source/Private/Invoke-Git.ps1, line 70 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-MbdzwzhEN2mF3bLZG-6:-Mbh6NsX36BIIrDh7fqh:b-3vfji6) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/517da028a74133afbabad50a336a7b3ef065f50a/source/Private/Invoke-Git.ps1#L70)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>                     Write-Warning -Message "  PWD: $workingDirectory"
>                     Write-Warning -Message "  git $argumentsJoined"
> ```

Can we add these to the localized string warning message above instead of having separate entries. Though, these looks like more as `Write-Debug` messages?
</blockquote></details>

Agreed. I was trying to keep with the theme of handling `ExitCode > 1` situations softer than going straight to `throw`. I've removed this entirely so the calling entry can take appropriate action.
___
*[source/Private/Invoke-Git.ps1, line 72 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-Mbe-h2pAMO-oZiP9rbQ:-Mbh7JKH3ekYfucW17sf:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/517da028a74133afbabad50a336a7b3ef065f50a/source/Private/Invoke-Git.ps1#L72)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> [string]
> ```

We should use full name `[System.String]`. Same on the line below too.
</blockquote></details>

Done.
___
*[source/Private/Invoke-Git.ps1, line 77 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-Mbe-twP6AC_ER76IBSF:-Mbh7xNU9K-djFmxIa9g:bh5xowc) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/517da028a74133afbabad50a336a7b3ef065f50a/source/Private/Invoke-Git.ps1#L77)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>  Write-Warning -Message "  OUTPUT: $invokeGitOutput"
> ```

What are your thoughts here? Why are we writing the standard output from git as a warning? 
</blockquote></details>

As mentioned above, it was my way of handling `ExitCode > 1`.
___
*[source/Private/Invoke-Git.ps1, line 79 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-Mbe0KrRDPmWuEu7w6C1:-Mbh86XjByvJaenlfMrU:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/517da028a74133afbabad50a336a7b3ef065f50a/source/Private/Invoke-Git.ps1#L79)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> if ([System.String]::IsNullOrWhiteSpace($invokeGitError) -eq $false)
> ```

We should add a new line before this line.
</blockquote></details>

Done.
___
*[source/Private/Invoke-Git.ps1, line 87 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-Mbe0cjr-69nqIJtSVM3:-Mbh87GQ3DrnVJ3O-nc0:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/517da028a74133afbabad50a336a7b3ef065f50a/source/Private/Invoke-Git.ps1#L87)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> catch {
> ```

We should have open brace on a separate line.
</blockquote></details>

Done.
___
*[source/Private/Invoke-Git.ps1, line 90 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-Mbe0YU8DOv4O7cL7iET:-Mbh7TMrDPdQ9KTDPADx:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/517da028a74133afbabad50a336a7b3ef065f50a/source/Private/Invoke-Git.ps1#L90)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>         $e = $_
>         Write-Error -Message $e.Exception.Message
> ```

It should be enough to do `throw $_`
</blockquote></details>

Done.
___
*[source/Private/Invoke-Git.ps1, line 92 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-Mbe0hKkEEhC1LJdlPdl:-Mbh88a92MNzlMN9Vtxe:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/517da028a74133afbabad50a336a7b3ef065f50a/source/Private/Invoke-Git.ps1#L92)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> finally {
> ```

We should have open brace on a separate line.
</blockquote></details>

Done.
___
*[source/Private/Invoke-Git.ps1, line 95 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-Mbe0zgB503BWf7BzF44:-MbhO6gzEzUTKkGsJv35:b-4f7r6) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/517da028a74133afbabad50a336a7b3ef065f50a/source/Private/Invoke-Git.ps1#L95)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>         $exitCode = $process.ExitCode
>         $process.Dispose()
> ```

Maybe we should check that `$process` is not null here if for some reason the `New-Object`failed? 
</blockquote></details>

Okay. Just to be safe I'll update it to:
```powershell
if ($process)
{
    $process.Dispose()
}
```

**Comment by johlju** [comment]
Did you close this by mistake? My thought was continue with this PR and merge it, then make a new PR with the suggestion to replace “git” with Invoke-Git in all other places. Just want to make sure I did not missunderstood 🙂

**Comment by phbits** [comment]
No, didn't close it by mistake. 🙂 I incorporated all the changes and proposed fixes from this PR into a new branch. Just opened a new PR #80 so you can take a look. Figured this would be easier/cleaner given that we both agreed on the new direction. 

That being said... err, typed, since you're the maintainer I'll leave it up to you for how you want to proceed. 🙂

**Comment by johlju** [comment]
It is easier for me to continue review on this PR (branch) otherwise I need to re-review everything again. Any additional changes to other files that you proposed, that was not part of this PR, can be pushed in another PR. 😊

So please continue to fix the review comments on this PR.

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76)* status: all files reviewed, 3 unresolved discussions (waiting on @phbits)

___
*[source/Private/Invoke-Git.ps1, line 45 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-Ma9fANH-vVZIBsXCx6B:-Mc3cH596ycQ8iEk4a8R:bhx8wpt) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/db4f536958e84a3c6932918c6f0b259e6fefce12/source/Private/Invoke-Git.ps1#L45)):*
<details><summary><i>Previously, phbits wrote…</i></summary><blockquote>

Agreed. Now that an object is being returned, if there's an error it will `throw`. 
</blockquote></details>

If this function is being modified for the caller to handle any error based of the exit code, then should we output a warning? Shouldn't it also be up to the caller to output any warning or throw an error?  :thinking: 
___
*[source/Private/Invoke-Git.ps1, line 14 at r7](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-Mc3aYur27Q8TfQYcgbF:-Mc3aYur27Q8TfQYcgbG:b2dqme0) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/50ae46736381d2a79387ffe54de814e80ad8ec24/source/Private/Invoke-Git.ps1#L14)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     .EXAMPLE
>         Invoke-Git clone https://github.com/X-Guardian/xActiveDirectory.wiki.git --quiet
>
>         Invokes the Git executable to clone the specified repository to the current working directory.
> ```
</details>


Can we update this example with the named parameters (and the mandatory one).
___
*[tests/unit/private/Invoke-Git.Tests.ps1, line 37 at r7](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-Mc3dW_Y8yFE_Ex5vAUX:-Mc3dW_Z6Xg2RuajGBSc:bu0muat) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/50ae46736381d2a79387ffe54de814e80ad8ec24/tests/unit/private/Invoke-Git.Tests.ps1#L37)):*
> ```
> $WorkingDirectory.FullName
> ```

Can't we just use `$TestDrive` here directly? Throughout.

**Review by phbits — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @johlju)

___
*[source/Private/Invoke-Git.ps1, line 45 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-Ma9fANH-vVZIBsXCx6B:-McPuRds8HWuZfhzrhgD:b-1d4sgi) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/db4f536958e84a3c6932918c6f0b259e6fefce12/source/Private/Invoke-Git.ps1#L45)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

If this function is being modified for the caller to handle any error based of the exit code, then should we output a warning? Shouldn't it also be up to the caller to output any warning or throw an error?  :thinking: 
</blockquote></details>

I agree. Unfortunately, this PR doesn't have `Invoke-Git` return an object, only the return code. The additional information, `StandardOutput` & `StandardError`, is needed for the caller and fixed in PR #80. This PR maintains pieces currently in use which is why it still returns the `ExitCode` and utilizes `Write-Warning` and `Write-Debug`. I cleaned this portion up in the latest commit which for some reason isn't showing up in Reviewable. :thinking: Once the latest revision shows up I think you'll find it suitable for this PR.
___
*[source/Private/Invoke-Git.ps1, line 14 at r7](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-Mc3aYur27Q8TfQYcgbF:-McPy0BG8C44iRsGuiTt:b6zrrk4) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/50ae46736381d2a79387ffe54de814e80ad8ec24/source/Private/Invoke-Git.ps1#L14)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>     .EXAMPLE
>         Invoke-Git clone https://github.com/X-Guardian/xActiveDirectory.wiki.git --quiet
>
>         Invokes the Git executable to clone the specified repository to the current working directory.
> ```

Can we update this example with the named parameters (and the mandatory one).
</blockquote></details>

Good catch!
___
*[tests/unit/private/Invoke-Git.Tests.ps1, line 37 at r7](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-Mc3dW_Y8yFE_Ex5vAUX:-McQ8B_rAkds0S2KuUoB:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/50ae46736381d2a79387ffe54de814e80ad8ec24/tests/unit/private/Invoke-Git.Tests.ps1#L37)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $WorkingDirectory.FullName
> ```

Can't we just use `$TestDrive` here directly? Throughout.
</blockquote></details>

Done.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-:-McZjYJd5K68weWbTzTZ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @phbits)

___
*[source/Private/Invoke-Git.ps1, line 45 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/76#-Ma9fANH-vVZIBsXCx6B:-McZjRRW0T9lo_Gd4Afo:b-qma8uh) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/db4f536958e84a3c6932918c6f0b259e6fefce12/source/Private/Invoke-Git.ps1#L45)):*
<details><summary><i>Previously, phbits wrote…</i></summary><blockquote>

I agree. Unfortunately, this PR doesn't have `Invoke-Git` return an object, only the return code. The additional information, `StandardOutput` & `StandardError`, is needed for the caller and fixed in PR #80. This PR maintains pieces currently in use which is why it still returns the `ExitCode` and utilizes `Write-Warning` and `Write-Debug`. I cleaned this portion up in the latest commit which for some reason isn't showing up in Reviewable. :thinking: Once the latest revision shows up I think you'll find it suitable for this PR.
</blockquote></details>

Lets' fix this in the next PR then.

**Pull request merged**
