### PR TITLE
Generate_Conceptual_Help: uses the correct path

### LINKED ISSUE #17: Generate_Conceptual_Help: Using wrong property for the parameter $ModuleVersion default value
#### Details of the scenario you tried and the problem that is occurring
Running the build task generates an issue when `gitversion` is installed. 

```plaintext
===============================================================================
                        GENERATE CONCEPTUAL HELP
This task generates conceptual help for DSC resources.
-------------------------------------------------------------------------------
  /build/Generate_Conceptual_Help
  C:\source\FileSystemDsc\output\RequiredModules\DscResource.DocGenerator\0.3.0\tasks\Generate_Conceptual_Help.build.ps1:103

        Project Path            = C:\source\FileSystemDsc
        Project Name            = FileSystemDsc
        Module Version          = 1.0.0-add-resource0001+Sha.a60d7ff1210a7eea658d3d3e02fea70a5a2c78c7.Date.2020-02-14
        Source Path             = C:\source\FileSystemDsc\source
        Built Module Path       = C:\source\FileSystemDsc\output\FileSystemDsc\1.0.0-add-resource0001+Sha.a60d7ff1210a7eea658d3d3e02fea70a5a2c78c7.Date.2020-02-14
Generating conceptual help for all DSC resources based on source.
ERROR: Could not find a part of the path 'C:\source\FileSystemDsc\output\FileSystemDsc\1.0.0-add-resource0001+Sha.a60d7ff1210a7eea658d3d3e02fea70a5a2c78c7.Date.2020-02-14\DSCResources\DSC_FileSystemAccessRule\en-US\about_FileSystemAccessRule.help.txt'.
At C:\source\FileSystemDsc\output\RequiredModules\DscResource.DocGenerator\0.3.0\DscResource.DocGenerator.psm1:509 char:23
+ ...       $output | Out-File -FilePath $savePath -Encoding 'ascii' -Force
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At C:\source\FileSystemDsc\output\RequiredModules\DscResource.DocGenerator\0.3.0\tasks\Generate_Conceptual_Help.build.ps1:103 char:1
+ task Generate_Conceptual_Help {
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At C:\source\FileSystemDsc\build.ps1:211 char:13
+             task $Workflow $WorkflowItem
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Build FAILED. 6 tasks, 1 errors, 0 warnings 00:00:03.4087934
Out-File : Could not find a part of the path 'C:\source\FileSystemDsc\output\FileSystemDsc\1.0.0-add-resource0001+Sha.a60d7ff1210a7eea658d3d3e02fea70a5a2c78c7.Date.2020-02-14\DSCResources\DSC_FileSys
temAccessRule\en-US\about_FileSystemAccessRule.help.txt'.
At C:\source\FileSystemDsc\output\RequiredModules\DscResource.DocGenerator\0.3.0\DscResource.DocGenerator.psm1:509 char:23
+ ...       $output | Out-File -FilePath $savePath -Encoding 'ascii' -Force
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], DirectoryNotFoundException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand
```

#### Steps to reproduce the problem
Running the build step with `gitversion` installed.

#### Expected behavior
Should build the path with the correct module version.

#### Current behavior
Instead of building the path with the module version `1.0.0` it building the path using the informational version outputted from `gitversion`, e.g. 
`1.0.0-add-resource0001+Sha.a60d7ff1210a7eea658d3d3e02fea70a5a2c78c7.Date.2020-02-14`.

#### Suggested solution to the issue

Change the following row to replace the property `InformationalVersion` with the property `MajorMinorPatch`.

https://github.com/dsccommunity/DscResource.DocGenerator/blob/eba282de474a2b661ee8b5c47d15f99333c598de/source/tasks/Generate_Conceptual_Help.build.ps1#L89

For reference, the output from `GitVersion`:
```
{
  "Major":1,
  "Minor":0,
  "Patch":0,
  "PreReleaseTag":"add-resource.1",
  "PreReleaseTagWithDash":"-add-resource.1",
  "PreReleaseLabel":"add-resource",
  "PreReleaseNumber":1,
  "WeightedPreReleaseNumber":30001,
  "BuildMetaData":1,
  "BuildMetaDataPadded":"0001",
  "FullBuildMetaData":"1.Branch.f-add-resource.Sha.a60d7ff1210a7eea658d3d3e02fea70a5a2c78c7",
  "MajorMinorPatch":"1.0.0",
  "SemVer":"1.0.0-add-resource.1",
  "LegacySemVer":"1.0.0-add-resource1",
  "LegacySemVerPadded":"1.0.0-add-resource0001",
  "AssemblySemVer":"1.0.0.0",
  "AssemblySemFileVer":"1.0.0.0",
  "FullSemVer":"1.0.0-add-resource.1+1",
  "InformationalVersion":"1.0.0-add-resource0001+Sha.a60d7ff1210a7eea658d3d3e02fea70a5a2c78c7.Date.2020-02-14",
  "BranchName":"f/add-resource",
  "Sha":"a60d7ff1210a7eea658d3d3e02fea70a5a2c78c7",
  "ShortSha":"a60d7ff",
  "NuGetVersionV2":"1.0.0-add-resource0001",
  "NuGetVersion":"1.0.0-add-resource0001",
  "NuGetPreReleaseTagV2":"add-resource0001",
  "NuGetPreReleaseTag":"add-resource0001",
  "VersionSourceSha":"694d615028f1031888871289554c2327b49ce54d",
  "CommitsSinceVersionSource":1,
  "CommitsSinceVersionSourcePadded":"0001",
  "CommitDate":"2020-02-14"
}
```

#### The operating system the target node is running
Windows 10

#### Version and build of PowerShell the target node is running
```
Name                           Value
----                           -----
PSVersion                      5.1.19041.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

#### Version of the module that was used
```
Name                     Version Path
----                     ------- ----
DscResource.DocGenerator 0.3.0   C:\source\FileSystemDsc\output\RequiredModules\DscResource.DocGenerator\0.3.0\DscResource.DocGenerator.psd1
```

### PR DESCRIPTION
**Pull request by johlju**
# Pull Request

### Pull Request (PR) description
- Fixes the build task `Generate_Conceptual_Help` to use the correct
  module version folder name for the built module path ([issue #17](https://github.com/dsccommunity/DscResource.DocGenerator/issues/17)).

#### This Pull Request (PR) fixes the following issues
- Fixes #17

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Documentation added/updated in README.md.
- [x] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated.
- [ ] Integration tests added/updated (where possible).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/18)

### CODE REVIEW

**Comment by johlju** [comment]
@ykuijs can we exchange reviews? 😃

**Comment by ykuijs** [comment]
Also you have to check out the failing tests for macOS and Linux

**Comment by johlju** [comment]
I missed that the tests was failing, will look into it later tonight.

**Comment by johlju** [comment]
@ykuijs 

> Shouldn't we have to make sure these generic variables (ModuleVersion and ModuleVersionFolder) are consistently available throughout the entire pipeline? Doesn't make much sense that you have to determine them each time you need it.

I agree with this, but I thinking that a build task should be a separate entity that can run without running something else first. New to these build tasks but when I wrote `Generate_Conceptual_Help` I thought that it should be able to be run without first running Sampler CI pipeline 🤔 
Each parameter in the build task can be set either as a script parameter, as a variable defined in a parent scope, or as an environment variable. If neither is available it uses the default value.

**Comment by ykuijs** [comment]
That makes totally sense, make it optional: Use configured variables from parent scopes or determine the correct value in this module.

**Comment by ykuijs** [comment]
Any clue when this issue will be fixed? Just tried adding this task to my resource and ran into the same issue :haha:

**Comment by johlju** [comment]
I just about to resolve the comments for this PR now 🙂 Was a crazy week. But now I'm on it!

**Comment by johlju** [comment]
@ykuijs this is ready for review again 😃

**Comment by johlju** [comment]
@ykuijs I will rebase PR #23 when this is merged

**Pull request merged**
