### PR TITLE
Fix class resource generation

### LINKED ISSUE #116: Cannot generate Wiki for inherited properties in class-based resource if class inherit more than once
#### Details of the scenario you tried and the problem that is occurring
Cannot generate the properties for the wiki when inherits more than once. See [DnsRecordNsScoped](https://github.com/dsccommunity/DnsServerDsc/wiki/DnsRecordNsScoped), this one inherits from DnsRecordNs, which inherits from DnsRecordBase and then inherits from DnsBaseProperties. It only get the properties from DnsRecordNsScoped  and DnsRecordNs, but missing properties from DnsRecordBase and DnsBaseProperties.

#### Steps to reproduce the problem
Build the repo DnsServerDsc

#### Expected behavior
Should output all inherited properties.

#### Current behavior
Missing properties.

#### Suggested solution to the issue
Loop through all parent classes.

#### The operating system the target node is running
n/a

#### Version and build of PowerShell the target node is running
n/a

#### Version of the module that was used
0.10.3

### LINKED ISSUE #126: Wiki generation for class-based resource puts parameters in random order
#### Details of the scenario you tried and the problem that is occurring
Wiki generation for class-based resource puts parameters in random order. Even more when a resource derive DSC properties from parent class. I suggest the properties are grouped in the order Key, Mandatory, Write, and last Read - for each group the properties are sorted in alphabetical ascending order.

#### Steps to reproduce the problem
See https://github.com/dsccommunity/SqlServerDsc/wiki/SqlAudit

#### Expected behavior
Better order of parameters.

#### Current behavior
Comes in the order they are in the code, with parent class properties first, then derived class's properties. 

#### Suggested solution to the issue
Sort the properties before writing them to mmarkdown.

#### The operating system the target node is running
n/a

#### Version and build of PowerShell the target node is running
n/a

#### Version of the module that was used
n/a

### PR DESCRIPTION
**Pull request by dan-hughes**
#### Pull Request (PR) description

Update documentation generation for Class Based Dsc Resources.
Reworked to not use Ast.

#### This Pull Request (PR) fixes the following issues

- Fixes #116 
- Fixes #126 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [ ] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.DocGenerator/163)

### CODE REVIEW

**Comment by dan-hughes** [comment]
@johlju, it's not ready yet but are you happy with the general approach? 

I've tested on DnsServerDsc, WSManDsc and ComputerManagementDsc and it seems to do what it should.

If you think this is good then I'll finish it off, add tests and clean up.

**Comment by johlju** [comment]
Just curious what the benefits are to not use AST? I would have thought that parsing AST would be the better approach.

**Comment by dan-hughes** [comment]
It was simpler to just call GetProperties() on the class which provides all declared and inherited properties in one command. This includes any properties from outside the module e.g. localizedData from DscResource.Base.

I started looking at it and what initially started as a relatively small change kept growing as each change had a knock on effect to not using AST.
The sorting fix is an easy one, it's generating the Docs for  multi level inheritance that took the work, especially if needing properties from outside the module. 

There is also scope for the type column in the table to link to a defined Class or Enum.

**Comment by johlju** [comment]
It the code will be simplified in the end, then I good with it. I can't see any downsides at this point.

**Comment by dan-hughes** [comment]
@johlju, can you give this a once over? 

It would be good to get it merged then configure a module to pull the pre-release to see what it looks like.

**Comment by dan-hughes** [comment]
@johlju, can you take a look please? Check I've added the correct tasks in build.yml.

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 20 of 21 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.DocGenerator/163)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-hughes)

___
*[`source/Private/Get-ClassResourcePropertyState2.ps1` line 18 at r2](https://reviewable.io/reviews/dsccommunity/DscResource.DocGenerator/163#-OBuREPX8J5ordkvzt1o:-OBuREPX8J5ordkvzt1p:b-w02h2j) ([raw file](https://github.com/dsccommunity/DscResource.DocGenerator/blob/b56de0f38267059259c4b2249b2d3612adc2e06b/source/Private/Get-ClassResourcePropertyState2.ps1#L18)):*
> ```PowerShell
>         Returns the property state for the property 'KeyName'.
> #>
> function Get-ClassResourcePropertyState2
> ```

Is there a reason the function name end with `2`? Maybe call it `Get-DscResourcePropertyAttribute` or something. Not sure what Key, Mandatory, NotConfigurable goes under what term, but 'attribute' might be good as any?

**Comment by johlju** [comment]
> @johlju, can you take a look please? Check I've added the correct tasks in build.yml.

It looks okay to me.

**Comment by dan-hughes** [comment]
> > Reviewed 20 of 21 files at r1, 1 of 1 files at r2, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.DocGenerator/163)_ status: all files reviewed, 1 unresolved discussion (waiting on @dan-hughes)
> 
> _[`source/Private/Get-ClassResourcePropertyState2.ps1` line 18 at r2](https://reviewable.io/reviews/dsccommunity/DscResource.DocGenerator/163#-OBuREPX8J5ordkvzt1o:-OBuREPX8J5ordkvzt1p:b-w02h2j) ([raw file](https://github.com/dsccommunity/DscResource.DocGenerator/blob/b56de0f38267059259c4b2249b2d3612adc2e06b/source/Private/Get-ClassResourcePropertyState2.ps1#L18)):_
> 
> > ```powershell
> >         Returns the property state for the property 'KeyName'.
> > #>
> > function Get-ClassResourcePropertyState2
> > ```
> 
> Is there a reason the function name end with `2`? Maybe call it `Get-DscResourcePropertyAttribute` or something. Not sure what Key, Mandatory, NotConfigurable goes under what term, but 'attribute' might be good as any?

It was a copy and paste of an AST function. I can rename though.

**Comment by dan-hughes** [comment]
@johlju, function name updated.

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.DocGenerator/163)* status: 18 of 21 files reviewed, 1 unresolved discussion (waiting on @dan-hughes)

___
*[`source/Private/Get-ClassResourcePropertyState2.ps1` line 18 at r2](https://reviewable.io/reviews/dsccommunity/DscResource.DocGenerator/163#-OBuREPX8J5ordkvzt1o:-OBulGzM13tHUsBH0KkH:b-mbme4f) ([raw file](https://github.com/dsccommunity/DscResource.DocGenerator/blob/b56de0f38267059259c4b2249b2d3612adc2e06b/source/Private/Get-ClassResourcePropertyState2.ps1#L18)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

It was a copy and paste of an AST function. I can rename though.
</blockquote></details>

Using `Get-ClassResourcePropertyType` is very close to the other function `Get-DscPropertyType` that returns the actual type of a property/parameter. This a "property" inside the of the `[DscResource()]` attribute, so maybe `Key` is attribute property? So, maybe `Get-DscResourceAttributeProperty`?

**Comment by dan-hughes** [comment]
@johlju, done.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.DocGenerator/163#-:-OBurM54-znrER4y3o2Z:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-hughes)

**Pull request merged**
